### PR TITLE
fix: make islinspace unit none

### LINKED ISSUE #3532: Set unit=None in islinspace
Currently, `islinspace` returns `unit='one'`:
```python
print(sc.islinspace(sc.linspace('x', 0, 1, 4)))
```
```
<scipp.Variable> ()       bool  [dimensionless]  True
```
This prevents using it in places where Python expects a boolean. Instead, it should, like other boolean operations, return `unit=None`.

### PR DESCRIPTION
**Pull request by jokasimr**
Fixes #3532

### CODE REVIEW

File: lib/core/include/scipp/core/element/util.h [hunk 1]
```diff
@@ -95,7 +95,7 @@ constexpr auto islinspace =
                         scipp::span<const int64_t>, scipp::span<const int32_t>,
                         scipp::span<const time_point>>,
                transform_flags::expect_no_variance_arg<0>,
-               [](const units::Unit &) { return units::one; },
+               [](const units::Unit &) { return units::none; },
```
Comment (SimonHeybrock) [inline lib/core/include/scipp/core/element/util.h:98]: `isarange` below appears to have the same problems. Are there more?

Comment (jokasimr) [reply lib/core/include/scipp/core/element/util.h:98]: :+1: I'll check.

The `isarange` seems to not be exposed to the python interface. Should it be?

Comment (SimonHeybrock) [reply lib/core/include/scipp/core/element/util.h:98]: Seems it was never needed...

**Review by SimonHeybrock — APPROVED** [review]
