### PR TITLE
Fix memory and threading problems of `histogram`

### LINKED ISSUE #2899: Missing multi-threading when histogramming 1-D inputs
## Context

Consider

```python
import scipp as sc
import numpy as np
N = 1000
var = sc.array(dims=['x','y','z'], values=np.random.normal(size=(N,N,N)))
```
This can be histogrammed using
```python
var.flatten(dims=['x', 'y', 'z'], to='dummy').hist(dummy=sc.linspace('dummy', -10,10,num=1000))
```
taking, e.g., 3 seconds. Major parts of this are not multi-threaded.

In contrast,
```python
var.flatten(dims=['y', 'z'], to='dummy').hist(dummy=sc.linspace('dummy', -10,10,num=1000)).sum('x')
```
takes only 1 second, as multi-threading over `x` is used.

The 3-D input with subsequent call to `flatten` is just for this example, to allow for comparison. The problem is not limited to such input, but is relevant for any 1-D input.

## Solution

Create pretend binning for 1-D inputs to the histogramming function. Note that https://github.com/scipp/scipp/blob/9b2ecf26243c5255efc7efa7c93cc64a45a181e7/lib/dataset/bins.cpp#L301-L324 already supports multiple bins along an existing binning dimension for the purpose of multi-threading (see the code comment). This would be leveraged by the solution, if we setup fake binning prior to this.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2899 and #2905. The latter change will actually *prevent* threading in some cases. Since this may anyway be a special case I kept it simple for now (can revisit later if this is a problem in practice).

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Here are updated timing results:

```python
import scipp as sc

table = sc.data.table_xyz(20 * 1_000_1000)
da = table.bin(x=1_000_000)
da.hist(x=1000)  # 800 ms -> 1.4 s
da.hist(x=10000)  # 7 s -> 1.4 s
da.hist(x=20000)  # 16 s -> 1.4 s
```

```python
import scipp as sc

table = sc.data.table_xyz(20 * 1_000_1000)
da = table.bin(x=10_000, y=1000)
_ = da.hist(y=1000)  # 7 s -> 4 s
_ = da.hist(y=2000)  # 13 s -> 3 s
_ = da.hist(y=10000)  # MemoryError -> 3 s
```

```python
import scipp as sc
import numpy as np
N = 1000
var = sc.array(dims=['x','y','z'], values=np.random.normal(size=(N,N,N)))
var.flatten(dims=['x', 'y', 'z'], to='dummy').hist(dummy=sc.linspace('dummy', -10,10,num=1000))  # 3s -> 800 ms
```

File: lib/dataset/bins.cpp [hunk 1]
```diff
@@ -211,6 +212,18 @@ Variable lookup_previous(const DataArray &function, const Variable &x, Dim dim,
                              "lookup_previous");
 }
 
+Variable pretend_bins_for_threading(const DataArray &da, Dim bin_dim) {
+  const auto dim = da.dims().inner();
+  const auto size = std::max(scipp::index(1), da.dims()[dim]);
+  // TODO automatic setup with reasonable bin count
```
Comment (jl-wynen) [inline lib/dataset/bins.cpp:218]: Would doing this help with threading? What is missing to do it?

File: lib/dataset/bins.cpp [hunk 2]
```diff
@@ -309,11 +322,22 @@ Variable histogram(const Variable &data, const Variable &binEdges) {
...
+  const auto nbin = binEdges.dims()[hist_dim] - 1;
+  if (indices.dims().contains(hist_dim)) {
+    // With large existing dim matching the new dim, we would create a large
+    // intermediate histogrammed result, which leads to performance and memory
+    // issues. This is a suboptimal (since it concatenates first) but simple way
+    // to avoid the problem.
+    // Note that unless there are additional dimensions, the following nested
+    // call to histogram will currently not use threading.
+    if (indices.dims().volume() * nbin > 100000000) // about 1 GByte
+      return histogram(concatenate(data, hist_dim), binEdges);
```
Comment (jl-wynen) [inline lib/dataset/bins.cpp:334]: Was it possible to histogram in this case before? (On a beefy workstation) If so, did this change impact run time significantly?

File: lib/dataset/bins.cpp (hunk 1 above)
Comment (SimonHeybrock) [reply lib/dataset/bins.cpp:218]: Coming up with a smart way determining a bin count, instead of using a hard-coded number with common factors of core counts?

File: lib/dataset/bins.cpp (hunk 2 above)
Comment (SimonHeybrock) [reply lib/dataset/bins.cpp:334]: See my earlier post in the PR thread. TL;DR No, there were cases where it crashed. Yes some runtimes are impacted significantly.

**Comment by SimonHeybrock** [comment]
I pushed another update, which affects this case:

```python
import scipp as sc

table = sc.data.table_xyz(20 * 1_000_1000)
da = table.bin(x=1_000_000)
da.hist(x=1000)  # 800 ms -> 1.4 s
da.hist(x=10000)  # 7 s -> 1.4 s
da.hist(x=20000)  # 16 s -> 1.4 s
```
The initial change did lose multi-threading in this case, but now we got it back, bringing timings to `1 s` (instead of `1.4 s`) in all cases.

File: lib/dataset/bins.cpp (hunk 2 above)
Comment (jl-wynen) [reply lib/dataset/bins.cpp]: But only negatively in one case. I think this is acceptable.

**Comment by jl-wynen** [comment]
> I pushed another update, which affects this case:
> 
> ```python
> import scipp as sc
> 
> table = sc.data.table_xyz(20 * 1_000_1000)
> da = table.bin(x=1_000_000)
> da.hist(x=1000)  # 800 ms -> 1.4 s
> da.hist(x=10000)  # 7 s -> 1.4 s
> da.hist(x=20000)  # 16 s -> 1.4 s
> ```
> 
> The initial change did lose multi-threading in this case, but now we got it back, bringing timings to `1 s` (instead of `1.4 s`) in all cases.

So it's 1s in all 3 cases? I think you forgot to update the code block...

**Comment by SimonHeybrock** [comment]
Yes, `1 s` in all cases.

**Review by jl-wynen — APPROVED** [review]

**Review by jl-wynen — APPROVED** [review]
