### PR TITLE
Require named operators in tranform

### LINKED ISSUE #1687: Extend Better Exception Messages
Follow up from https://github.com/scipp/scipp/pull/1686 which introduced operation names into transform exception messages.

Currently name is only provided for template usage of variable operations using transform. Make new `name` argument required and provide name in all breaking cases.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
- Fixes #1687 by making operator name argument in `transform` and friends mandatory.
- Generate code in a few more cases.
- Remove `sc.geometry.x` etc., in favor of new properties added recently.

### CODE REVIEW

File: variable/include/scipp/variable/transform.h [hunk 1]
```diff
@@ -644,8 +644,7 @@ template <bool dry_run> struct in_place {
 /// equivalent to std::transform with a single input range and an output range
 /// identical to the input range, but avoids potentially costly element copies.
 template <class... Ts, class Var, class Op>
-void transform_in_place(Var &&var, Op op,
-                        const std::string_view &name = "operation") {
+void transform_in_place(Var &&var, Op op, const std::string_view &name) {
```
Comment (jl-wynen) [inline variable/include/scipp/variable/transform.h:647]: As extra cleanup: you would normally take string_views by value.

File: variable/operations.cpp [hunk 2]
```diff
@@ -36,16 +36,14 @@ Variable copy(const Variable &var, Variable &&out) {
...
 Variable masked_to_zero(const Variable &var, const Variable &mask) {
-  return transform(var, mask, element::convertMaskedToZero);
+  return variable::transform(var, mask, element::convertMaskedToZero,
+                             "masked_to_zero");
 }
 
 namespace geometry {
 Variable position(const Variable &x, const Variable &y, const Variable &z) {
-  return transform(x, y, z, element::geometry::position);
+  return transform(x, y, z, element::geometry::position, "linalg.position");
```
Comment (jl-wynen) [inline variable/operations.cpp:45]: Why 'linalg'?

**Review by jl-wynen — APPROVED** [review]
Good idea, I have only minor comments.

File: variable/operations.cpp (hunk 2 above)
Comment (SimonHeybrock) [reply variable/operations.cpp:45]: No idea, I think I wanted to rename `geometry` to `linalg` for consistency with numpy, but then didn't. I'll change.

File: variable/creation.cpp [hunk 3]
```diff
@@ -36,6 +36,8 @@ Variable empty_like(const Variable &prototype,
 
 Variable special_like(const Variable &prototype, const FillValue &fill) {
   const char *name = "special_like";
+  if (fill == FillValue::Default)
```
Comment (jl-wynen) [inline variable/creation.cpp:39]: You can use a switch instead. Then clang will warn if an enum field is not handled.

Comment (SimonHeybrock) [reply variable/creation.cpp:39]: I don't think that is true for all compilers? Or is it in a recent version of the standard? Also, what if someone cast an int to the enum?

Comment (jl-wynen) [reply variable/creation.cpp:39]: No, AFAIK only clang does it. But I occasionally build with clang and fix its warnings, so this is better than nothing.

> Also, what if someone cast an int to the enum?

That only makes sense if they cast to one of the defined fields, so this would still be covered.

Comment (SimonHeybrock) [reply variable/creation.cpp:39]: Well, but what if they don't? Returning an uninitialized value?

Comment (jl-wynen) [reply variable/creation.cpp:39]: What returns an uninitialised value? It doesn't matter if you use a switch of if-else, if you forget a case, bad things happen.

Comment (SimonHeybrock) [reply variable/creation.cpp:39]: Ok, so you would still leave the `throw`?

Comment (jl-wynen) [reply variable/creation.cpp:39]: Yes, use a `switch` and let it fall through to `throw` if no case matches.

Comment (jl-wynen) [reply variable/creation.cpp:39]: But don't use `default`. That disables the compiler check.
