### PR TITLE
Address `convert_with_calibration` issues

### LINKED ISSUE #885: `neutron.diffraction.convert_with_calibration` does not fail on incorrect units
```python
def test_neutron_convert_with_calibration():
    tof = sc.Dataset(
        {
            "counts":
            sc.Variable(dims=[Dim.Spectrum, Dim.Tof],
                        values=np.array([[1, 2, 3], [4, 5, 6]]),
                        unit=sc.units.counts)
        },
        coords={
            Dim.Tof:
            sc.Variable(dims=[Dim.Tof],
                        values=np.array([4000, 5000, 6100, 7300]),
                        unit=sc.units.us)
        })

    cal = sc.Dataset({
        "tzero":
        sc.Variable(dims=[Dim.Spectrum],
                    values=np.array([1.1, 2.2]),
                    unit=sc.units.us),
        "difc":
        sc.Variable(dims=[Dim.Spectrum], values=np.array([3.3, 4.4]))
    })

    out = sc.neutron.diffraction.convert_with_calibration(tof, cal)

    assert out["counts"].dims == [Dim.Spectrum, Dim.DSpacing]
    assert out.coords[Dim.DSpacing].unit == sc.units.angstrom
```

The unit of the `DSpacing` coordinate remains `us`.

### PR DESCRIPTION
**Pull request by DanNixon**
- Adds validation for calibration dataset
- Add unit test for Python export

Fixes #885

### CODE REVIEW

File: neutron/diffraction/convert_with_calibration.cpp [hunk 1]
```diff
@@ -71,11 +71,20 @@ template <class T> T convert_with_calibration_impl(T d, Dataset cal) {
   return d;
 }
 
+void validate_calibration(const Dataset &cal) {
+  if (cal["tzero"].unit() != scipp::units::us)
+    throw except::UnitError("tzero must have units of `us`");
+  if (cal["difc"].unit() != scipp::units::us / scipp::units::angstrom)
+    throw except::UnitError("difc must have units of `us / angstrom`");
```
Comment (SimonHeybrock) [inline neutron/diffraction/convert_with_calibration.cpp]: Will break if someone starts to use, e.g., `ms` as their unit. Not sure how likely that is, so maybe we can ignore that.

File: python/tests/test_neutron.py [hunk 2]
```diff
@@ -54,6 +54,38 @@ def test_neutron_convert_out_arg():
     assert dspacing is d
 
 
+def test_neutron_convert_with_calibration():
```
Comment (SimonHeybrock) [inline python/tests/test_neutron.py]: Move this test into `diffraction/` subfolder?

Comment (DanNixon) [reply python/tests/test_neutron.py]: I'd say no since the export is not in a `diffraction` directory.

Comment (SimonHeybrock) [reply python/tests/test_neutron.py]: Given that this is Python code, wouldn't it make more sense to follow the Python module structure, rather than the place of some C++ code?

Comment (DanNixon) [reply python/tests/test_neutron.py]: Since this is a developer focused thing I think it makes more sense to match file structure (to keep the test and the thing that is tested in similar locations).

Comment (DanNixon) [reply python/tests/test_neutron.py]: Or maybe the exports should be made to match the intended module structure.

Comment (DanNixon) [reply python/tests/test_neutron.py]: Or maybe the exports should be made to match the intended module structure.

Comment (DanNixon) [reply python/tests/test_neutron.py]: Restructuring the exports may need more consideration as the `python` directory is already a mix of benchmarks, tests, Python and C++. For now I've just made the Python tests match the module structure.
