### PR TITLE
Fix `subspan_view` for slices and other shape/stride related ops and other bug in `histogram`

### LINKED ISSUE #2029: `histogram` incorrect for views of 2d data
```python
import numpy as np
import scipp as sc
N = 500
data = sc.DataArray(
    data=sc.Variable(dims=['pixel','event'], unit='counts', values=10*np.random.rand(10,N)),
    coords={'x':sc.Variable(dims=['event'], unit='m', values=np.random.rand(N))})
edges = sc.linspace(dim='x', unit='m', start=0.0, stop=1.0, num=10)
tot = sc.sum(sc.histogram(data, bins=edges))
a = sc.sum(sc.histogram(data['event',:200], bins=edges))
b =sc.sum(sc.histogram(data['event',200:], bins=edges))
print(tot, a+b)
```
Gives different results. If we copy the views that are used as inputs to `histogram` first, it is correct.

### LINKED ISSUE #2033: `histogram` of dense data ignores mask if histogramming dim does not match output dim
Mask ignored:
```python
import numpy as np
import scipp as sc
N = 500
data = sc.DataArray(
    data=sc.Variable(dims=['pixel','event'], unit='counts', values=10*np.random.rand(2,N)),
    masks={'mask':sc.ones(dims=['event'], dtype='bool', shape=[N])},
    coords={'x':sc.Variable(dims=['event'], unit='m', values=np.random.rand(N))})
edges = sc.linspace(dim='x', unit='m', start=0.0, stop=1.0, num=10)
sc.histogram(data, bins=edges)
```

Mask applied correctly:
```python
import numpy as np
import scipp as sc
N = 500
data = sc.DataArray(
    data=sc.Variable(dims=['pixel','x'], unit='counts', values=10*np.random.rand(2,N)),
    masks={'mask':sc.ones(dims=['x'], dtype='bool', shape=[N])},
    coords={'x':sc.Variable(dims=['x'], unit='m', values=np.random.rand(N))})
edges = sc.linspace(dim='x', unit='m', start=0.0, stop=1.0, num=10)
sc.histogram(data, bins=edges)
```

The problem is simple to fix, just using wrong dim label when considering masks.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2029.

The bug was the assumption that shape defines offsets/strides, which was correct prior to the shared-buffer rewrite. Now we have to consider strides directly. I fear we may have other instances of code that make similar wrong assumptions, not sure if there is a way to locate those.

Fixes  #2033.

### CODE REVIEW

File: variable/subspan_view.cpp [hunk 1]
```diff
@@ -68,17 +68,21 @@ Variable subspan_view_impl(Var &var, const Dim dim, Args &&... args) {
       var.dtype(), var, dim, args...);
 }
 
+auto make_range(const scipp::index num, const scipp::index stride,
+                const Dim dim) {
+  return cumsum(broadcast(stride * units::one, {dim, num}), dim,
+                CumSumMode::Exclusive);
```
Comment (jl-wynen) [inline variable/subspan_view.cpp:74]: We should implement `arange` in C++ so we don't have to do things like this.

**Review by jl-wynen — APPROVED** [review]
