### PR TITLE
Reduction performance bug

### LINKED ISSUE #1517: sc.sum is 5x-20x slower than numpy
Screenshot at 2021-01-08 15-22-01

Summing over the `z` dimension yields 566 ms, 5x slower than numpy's 106 ms

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #1517 by avoiding bad transpose of dimension by `merge`.

### CODE REVIEW

**Comment by jl-wynen** [comment]
Do you have benchmark results? I don't see how this can improve performance since `merge` keeps the order of dimensions in the benchmark fixed.

**Comment by SimonHeybrock** [comment]
> Do you have benchmark results? I don't see how this can improve performance since `merge` keeps the order of dimensions in the benchmark fixed.

The problem was the the *old* `merge` implementation caused a transpose:
- Suppose we have YX data and sum Y.
- The output of `accumulate_in_place` is X.
- This is the first arg that `transform_in_place` passes to `merge`, i.e., it called `merge(X, YX)`.
- The old implementation made the first arg "dominate" the order, so it resulted in `XY`, iterating the input in transposed order.

I see a 10x speedup of the benchmark (once out of cache).

File: core/dimensions.cpp [hunk 1]
```diff
@@ -180,15 +180,28 @@ int32_t Dimensions::index(const Dim dim) const {
...
 /// Throws if there is a mismatching dimension extent.
 Dimensions merge(const Dimensions &a, const Dimensions &b) {
-  auto out(a);
-  for (const auto dim : b.labels()) {
-    if (a.contains(dim)) {
+  Dimensions out;
+  auto it = b.labels().begin();
+  auto end = b.labels().end();
+  for (const auto dim : a.labels()) {
+    // add any labels appearing *before* dim
```
Comment (SimonHeybrock) [inline core/dimensions.cpp:187]: @jl-wynen This is the relevant changed behavior: It tries to keep outer dims as outer dims, but otherwise favors order as given by `a`.

**Comment by jl-wynen** [comment]
When it transposed, did it create a copy of `b`?

**Comment by SimonHeybrock** [comment]
> When it transposed, did it create a copy of `b`?

No, no copy, this was just determining the "iter dims" that where used by `MultiIndex`.

**Comment by jl-wynen** [comment]
So does the improvement come from a better memory access or from doing less work when indexing?

**Comment by SimonHeybrock** [comment]
> So does the improvement come from a better memory access or from doing less work when indexing?

From better (ordered, rather than transposed) memory access of a 2d (or higher) array.

**Comment by jl-wynen** [comment]
Ok

**Review by jl-wynen — APPROVED** [review]

**Review by nvaytet — APPROVED** [review]
