### PR TITLE
DataArray and fixes for Dataset binary operations

### LINKED ISSUE #417: Coord checks in Dataset operations are too restrictive
Consider for example the case of adding a constant to each data item:

```cpp
  const auto x = makeVariable<double>({Dim::X, 3}, {1, 2, 3});
  Dataset a;
  Dataset b;
  a.setCoord(Dim::X, x);
  a.setData("data1", x);
  a.setData("data2", x);
  b.setData("data1", makeVariable<double>(1.0));
  b.setData("data2", makeVariable<double>(2.0));
```
This currently fails due to mismatching coordinates.

The same would arise in operations like:

```python
delta = d - mean(d, Dim.X)
```

### LINKED ISSUE #418: Binary operations with sparse data should fail if there are no values
Operations like `+=` on, e.g., `DataConstProxy` do nothing if there is no data (i.e., a coord-only sparse item). However, this does not make sense, it should throw instead.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
While attempting to resolve two issues with binary operations, I realized that a lot of complexity that has accumulated recently in `dataset.cpp` and related code can be avoid by adding `DataArray` (see #245) and some other helpers.

- Fixes #418.
- Fixes #417.

The implementation of `DataArray` (and its Python bindings) are deliberately incomplete for now (and direct tests are missing). It is not essential to have more features, and I think we can postpone those changes. My plan is to improve our units tests for dataset operations, it may be that I will do the remaining work for `DataArray` while that is done.

@igudich @DanNixon I am requesting your review, since this refactors parts of the code you wrote recently.

@OwenArnold Please also have a look, since the addition of `DataArray` and some of the applied logic is a central concept.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
One thing to not is that `dataset1 + dataset2` will now drop all coords and labels that not part of at least one data item. For example, if you have a Y coord, but all data depends on on X, the result will not contain the Y coord.

File: core/dataset.cpp [hunk 1]
```diff
@@ -232,72 +232,46 @@ void Dataset::setData(const std::string &name, Variable data) {
...
-    return true;
-  const auto dsCoords{dataset.coords()};
-  const auto otCoords{other.coords()};
-  const auto &dsItems = dsCoords.items();
-  for (const auto & [ d, v ] : otCoords) {
-    if (auto iter = dsItems.find(d); iter == dsItems.end()) {
-      return false;
+/// Set (insert or replace) data item with given name.
+///
+/// Coordinated, labels, and attributes of the data array are added to the
```
Comment (igudich) [inline core/dataset.cpp]: Can't see if attributes are added.

Comment (SimonHeybrock) [reply core/dataset.cpp]: Good point, they are not, since that would require merging rules, which we have not defined yet (and may never). I will fix the doxygen, it is weong.
