### PR TITLE
Arithmetic type conversion/support fixes

### LINKED ISSUE #1114: Binary arithmetic between float and int types
Here is a trivial case which should "just work" from a user perspective. 

```
foo = sc.Dataset()
foo.coords[Dim.Tof] = sc.Variable([Dim.Tof],
                   values=np.arange(1, 10, 1, dtype=np.float64))

foo.coords[Dim.Tof] += 5
```

Instead we get the following message:
`Cannot apply operation to item dtypes float64 int32 `
(Note this message should be improved to say something like `between a float64 and int32`, `dtype` is a C++ idiom)

In my opinion this is an API bug for the following reasons:
- We are adding to a int to a float so precision can't be lost (the same isn't true to other way)
- Python supports this operation normally
- It violates principle of least astonishment 

I can see users starting to take the path of least resistance leading to casts like this before every operation out of habit:
`foo.coord[Dim.Tof] += float(5)` 

In `transform.h` and `apply.h` we should use something like
```
if constexpr (!std::is_same_v(a, b)){
    if constexpr (!std::is_convertible<a, b>::value || std::is_floating_point<a>::value){
         throw ...;
    }
    // Trivially convert b -> a then use b for the rest
    decltype(a) b_converted(a);
```

This allows us to convert `int` -> `float` but prevents us losing precision if we try to convert a `float` -> `any`

### LINKED ISSUE #1265: Integer division is floordiv instead of truediv
```python
import scipp as sc
2 * sc.units.m / (3 * sc.units.m)
```
Gives `0`. Should return float 0.666.. to be compliant with Python 3.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
The overall approach is to be consistent with Python 3 and numpy (in particular `truediv`). This implies that the behavior on the C++ side is unusual, but in practice this should not be an issue. Note that we are not 100% numpy compliant yet, e.g., numpy int32/float32 gives float64, whereas scipp still gives float32.

- Fixes #1265.
- Fixes #1114.

### CODE REVIEW

File: core/test/element_arithmetic_test.cpp [hunk 1]
```diff
@@ -43,3 +43,35 @@ TEST_F(ElementArithmeticTest, non_in_place) {
...
 TEST_F(ElementArithmeticTest, unary_minus) { EXPECT_EQ(unary_minus(a), -a); }
+
+TEST(ElementArithmeticIntegerDivisionTest, truediv) {
+  // 32 bit ints gives double not float, consistent with numpy
+  EXPECT_TRUE((std::is_same_v<decltype(divide(int32_t{}, int32_t{})), double>));
+  EXPECT_TRUE((std::is_same_v<decltype(divide(int64_t{}, int64_t{})), double>));
+}
+
+TEST(ElementArithmeticIntegerDivisionTest, truediv_32bit) {
+  const int32_t a = 2;
```
Comment (nvaytet) [inline core/test/element_arithmetic_test.cpp:54]: I'm slightly confused as to why we are checking division of integer by integer, if we state above that
```
we do *not* support any integer type as left-hand-side, to match Python 3 and numpy "truediv" behavior.
```

Comment (nvaytet) [reply core/test/element_arithmetic_test.cpp:54]: ok, i think i misunderstood. The int on the left had side is only for in-place, correct?

Comment (SimonHeybrock) [reply core/test/element_arithmetic_test.cpp:54]: Correct. 👍
