### PR TITLE
Fix bug in linspace optimization of `bin` and `hist`

### LINKED ISSUE #2922: `bin` with "linspace" edges broken for large values outside bin bounds
This happens for 2 or more bins:

```python
import scipp as sc
table = sc.data.table_xyz(10)
table.coords['x'].values[0] = 1e16
da = table.bin(x=sc.linspace('x', 0.0, 1.0, 3, unit='m', dtype='float64'))
da
```

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2922. This was caused by int overflows, wrapping, e.g., a large positive to a negative.

Please have a very close look, this is not the first time this code piece is buggy.

### CODE REVIEW

File: lib/core/include/scipp/core/element/histogram.h [hunk 1]
```diff
@@ -65,14 +66,17 @@ static constexpr auto histogram = overloaded{
         const auto [offset, nbin, scale] = core::linear_edge_params(edges);
         for (scipp::index i = 0; i < scipp::size(events); ++i) {
           const auto x = events[i];
+          // Explicitly check for x outside edges here as otherwise we
+          // may run into an integer overflow when converting the "bin"
+          // computation result to `Index`.
+          if (x < edges.front() || x >= edges.back())
+            continue;
```
Comment (jl-wynen) [inline lib/core/include/scipp/core/element/histogram.h:73]: Given that this fix is nearly identical in `bin` and `histogram`, is it possible to extract the common code into a function that computes the target `bin`?

File: tests/binning_test.py [hunk 2]
```diff
@@ -760,3 +760,56 @@ def test_make_binned_via_bin_optimized_path_yields_equivalent_results(params):
...
+
+
+def test_bin_with_explicit_lower_precision_drops_rows_outside_domain():
+    table = sc.data.table_xyz(100)
+    x = sc.linspace('x', 0.0, 1.0, 3, unit='m', dtype='float32')
+    da = table.bin(x=x)
+    size = da.bins.size().sum().value
+    table.coords['x'].values[0] = 2.0 * np.finfo(np.float32).max
+    da = table.bin(x=x)
+    assert da.bins.size().sum().value == size - 1
```
Comment (jl-wynen) [inline tests/binning_test.py:815]: None of these tests check that the correct element was dropped, only that the size was reduced by 1. Instead, you could slice out the bad element and group/bin/hist the slice and use that as the expected result.

File: lib/core/include/scipp/core/element/histogram.h (hunk 1 above)
Comment (SimonHeybrock) [reply lib/core/include/scipp/core/element/histogram.h:73]: >     * 5-10% for `bin`

Scratch that, the implementation in this PR has the 5% regression (no visible difference when multi-threading is on), but extracting the function seems to perform as the original. Need to investigate more.

Comment (SimonHeybrock) [reply lib/core/include/scipp/core/element/histogram.h]: I rewrote it slightly, and see no significant performance impact. There *may* be a very small slowdown, in particular for `hist` of the order of 5-10%, but I doubt it would be relevant in practice (i.e., with multi-threading).

Comment (jl-wynen) [reply lib/core/include/scipp/core/element/histogram.h]: Looks good

**Review by jl-wynen — APPROVED** [review]
