### PR TITLE
Fix segfault in flatten with empty dims

### LINKED ISSUE #2828: Segfault in `DataArray.flatten` when flattening zero dimensions
```python
import scipp as sc

sc.arange('x', 10).flatten(dims=[], to='abc')  # ok
sc.DataArray(sc.arange('x', 10)).flatten(dims=[], to='abc')  # segfault
```

### PR DESCRIPTION
**Pull request by jl-wynen**
Fixes #2828

Also fixes detection of bad dim labels, see `ReshapeTest.flatten_dim_not_in_input`.

### CODE REVIEW

File: lib/dataset/shape.cpp [hunk 1]
```diff
@@ -272,20 +272,39 @@ DataArray fold(const DataArray &a, const Dim from_dim,
...
-    const auto var =
+    auto var =
         (&in == &a.data()) ? in : maybe_broadcast(in, from_labels, a.dims());
     const auto bin_edge_dim =
         bin_edge_in_from_labels(in, a.dims(), from_labels);
     if (bin_edge_dim != Dim::Invalid) {
       return flatten_bin_edge(var, from_labels, to_dim, bin_edge_dim);
     } else if (var.dims().contains(from_labels.front())) {
+      // maybe_broadcast ensures that all variables contain
+      // all dims in from_labels, se only need to check the first.
```
Comment (SimonHeybrock) [inline lib/dataset/shape.cpp:304]:
```suggestion
      // all dims in from_labels, so only need to check the first.
```
? But which `first` is this referring to?

**Review by SimonHeybrock — APPROVED** [review]

File: lib/dataset/shape.cpp (hunk 1 above)
Comment (jl-wynen) [reply lib/dataset/shape.cpp]: Updated the comment
