### PR TITLE
Dry run to prevent partially applied in-place modifications

### LINKED ISSUE #1831: Add dry-run mechanism to prevent data modification before potential read-only fails from meta data
Required for Dataset and possibly DataArray.

### PR DESCRIPTION
**Pull request by OwenArnold**
fixes #1831 As can result from the new read-only mechanism

### CODE REVIEW

File: dataset/test/slice_test.cpp [hunk 1]
```diff
@@ -711,3 +711,67 @@ TEST_F(CoordToAttrMappingTest, DatasetConstView) {
...
+                       except::DimensionError);
+  // We test for a partially-applied modification as a result of an aborted
+  // transaction Check that "a" is NOT getting modified before operation falls
+  // over on "b".
+  EXPECT_EQ(original, ds); // Failed op should have no effect
+
+  EXPECT_THROW_DISCARD(ds.setSlice(Slice{Dim::X, 0}, point),
+                       except::DimensionError);
+  EXPECT_EQ(original, ds); // Failed op should have no effect
+}
```
Comment (SimonHeybrock) [inline dataset/test/slice_test.cpp:777]: These should probably go into `set_slice_test.cpp`?

File: dataset/data_array.cpp [hunk 2]
```diff
@@ -90,9 +90,13 @@ DataArray DataArray::slice(const Slice &s) const {
           m_attrs->slice(s).merge_from(out_attrs), m_name};
 }
 
-DataArray &DataArray::setSlice(const Slice &s, const DataArray &array) {
+void DataArray::validateSlice(const Slice &s, const DataArray &array) {
   expect::coordsAreSuperset(slice(s), array);
-  // TODO Need dry-run mechanism for mask handling?
+  masks().validateSlice(s, array.masks());
```
Comment (SimonHeybrock) [inline dataset/data_array.cpp:95]: Do we also need to check that `setSlice` on the data could not fail? Is suppose the coord check is catching a lot of potential problems, but not all, e.g., if only one arg has variances, or if units differs? If these aspects are not checked there are two problems:

- Masks get modified.
- If this is applied to dataset items, other dataset items may have beed modified already.

Comment (SimonHeybrock) [reply dataset/data_array.cpp:95]: I suppose basically we also need `Variable::validateSlice`?

File: dataset/map_view.cpp [hunk 3]
```diff
@@ -170,6 +170,11 @@ Dict<Key, Value> &Dict<Key, Value>::setSlice(const Slice s, const Dict &dict) {
                                    to_string(s.dim()) + "'.");
     }
   }
```
Comment (SimonHeybrock) [inline dataset/map_view.cpp:172]: Similar to potential issues with data mentioned above: Do we also need to call `Variable::validateSlice` for every mask that neds updating?

File: dataset/dataset.cpp [hunk 4]
```diff
@@ -152,14 +152,20 @@ Dataset Dataset::slice(const Slice s) const {
...
 
 Dataset &Dataset::setSlice(const Slice s, const Dataset &data) {
-  // TODO Need dry-run mechanism here?
+  // Validate slice on all items as a dry-run
+  for (const auto &item : data)
+    (*this)[item.name()].validateSlice(s, item);
+  // Only if all items checked for dry-run does modification go-ahead
   for (const auto &item : data)
     (*this)[item.name()].setSlice(s, item);
   return *this;
```
Comment (SimonHeybrock) [inline dataset/dataset.cpp:161]: Wondering if it is worth saving some cost here. As it is now, in a dataset with N items, we do 2N coord comparisons, where actually only 1 is needed. To avoid this we can:

1. Call `expect::coordsAreSuperset(slice(s), data);` here (+1 coord compare).
2. Call `validateSlice` on entries of `m_items` and `data.m_items`, since these do not contain coords (-N coord compares)
3. Call `setSlice` on entries of `m_items` and `data.m_items`

Same technique can be applied below.

File: variable/variable.cpp [hunk 5]
```diff
@@ -123,7 +123,36 @@ Variable Variable::slice(const Slice params) const {
   return out;
 }
 
+void Variable::validateSlice(const Slice &s, const Variable &data,
+                             const std::string &parent_key) const {
```
Comment (SimonHeybrock) [inline variable/variable.cpp:127]: This is a really odd member, I don't think it should exist with this signature. Can we keep the checks that require the parent key in `Dict::validateSlice`?

Comment (OwenArnold) [reply variable/variable.cpp:127]: Agreed. This does not make good sense. Will change.

File: dataset/dataset.cpp [hunk 6]
```diff
@@ -152,16 +152,24 @@ Dataset Dataset::slice(const Slice s) const {
 }
 
 Dataset &Dataset::setSlice(const Slice s, const Dataset &data) {
-  // TODO Need dry-run mechanism here?
-  for (const auto &item : data)
-    (*this)[item.name()].setSlice(s, item);
+  // Validate slice on all items as a dry-run
+  expect::coordsAreSuperset(slice(s), data);
+  for (const auto &[name, item] : m_data)
+    item.validateSlice(s, data[name]);
```
Comment (SimonHeybrock) [inline dataset/dataset.cpp:158]:
```suggestion
    item.validateSlice(s, data.m_data[name]);
```
or else you will have the coords of the RHS included?

File: dataset/dataset.cpp [hunk 7]
```diff
@@ -152,16 +152,24 @@ Dataset Dataset::slice(const Slice s) const {
...
+  // Only if all items checked for dry-run does modification go-ahead
+  for (auto &[name, item] : m_data)
+    item.setSlice(s, data[name]);
```
Comment (SimonHeybrock) [inline dataset/dataset.cpp:161]:
```suggestion
    item.setSlice(s, data.m_data[name]);
```
?

File: dataset/except.cpp [hunk 8]
```diff
@@ -40,12 +40,23 @@ void throw_mismatch_error(const std::pair<const Dim, Variable> &expected,
...
+} // namespace
+
+void coordsAreSuperset(const DataArray &a, const DataArray &b) {
+  coordsAreSuperset(a.coords(), b.coords());
+}
+void coordsAreSuperset(const Dataset &a, const Dataset &b) {
+  coordsAreSuperset(a.coords(), b.coords());
+}
+void coordsAreSuperset(const Dataset &a, const DataArray &b) {
+  coordsAreSuperset(a.coords(), b.coords());
```
Comment (SimonHeybrock) [inline dataset/except.cpp:59]: Maybe it would be better to require from the caller to use
```python
coordsAreSuperset(a.coords(), b.coords());
```
?

File: dataset/data_array.cpp [hunk 9]
```diff
@@ -90,9 +90,14 @@ DataArray DataArray::slice(const Slice &s) const {
...
+void DataArray::validateSlice(const Slice &s, const DataArray &array) const {
   expect::coordsAreSuperset(slice(s), array);
-  // TODO Need dry-run mechanism for mask handling?
+  data().validateSlice(s, array.data());
+  masks().validateSlice(s, array.masks());
+}
+
+DataArray &DataArray::setSlice(const Slice &s, const DataArray &array) {
+  validateSlice(s, array);
   masks().setSlice(s, array.masks());
```
Comment (SimonHeybrock) [inline dataset/data_array.cpp:101]: On our short call this morning we had concluded that we are avoiding double-checking things such as coords, but here we actually check masks a second time? Maybe we should also validate coords and data directly here, then attempt `masks().setSlice()` which would call the same as the last line of `DataArray::validateSlice` above?

Comment (OwenArnold) [reply dataset/data_array.cpp:103]: I'm not clear on what you are suggesting here. Maybe best discussed on a call.

**Review by SimonHeybrock — APPROVED** [review]
