### PR TITLE
Better unit error in to_unit when variable unit is None

### LINKED ISSUE #2435: Unclear exceptions when `unit==None`
For example:
```python
import scipp as sc
sc.to_unit(sc.index(5), unit='m')
```
throws `RuntimeError: bad optional access`.

Should throw a `UnitError` instead (something like "expected a unit, got `None`).

### PR DESCRIPTION
**Pull request by nvaytet**
Fixes #2435

### CODE REVIEW

File: lib/variable/to_unit.cpp [hunk 1]
```diff
@@ -29,8 +29,12 @@ Variable to_unit(const Variable &var, const units::Unit &unit,
                  const CopyPolicy copy) {
   if (unit == var.unit())
     return copy == CopyPolicy::Always ? variable::copy(var) : var;
-  const auto scale = llnl::units::quick_convert(
-      variableFactory().elem_unit(var).underlying(), unit.underlying());
+  const auto var_unit = variableFactory().elem_unit(var);
+  if (var_unit == units::none)
+    throw except::UnitError(
+        "Conversion from a `none` unit to another unit is not permitted.");
```
Comment (SimonHeybrock) [inline lib/variable/to_unit.cpp:35]: - Refer to `None`, not `none`.
- I would not call it "none unit", `None` means there is no unit.

Comment (nvaytet) [reply lib/variable/to_unit.cpp:35]: "Unit conversion is not permitted as the input variable has no unit." ?

Comment (SimonHeybrock) [reply lib/variable/to_unit.cpp:35]: Something like that.
