### PR TITLE
Prevent bin data use with rebin

### LINKED ISSUE #1536: rebin should throw for event data
Issue found while refactoring from-mantid-to-scipp notebook

```python
import mantid.simpleapi as mantid
import numpy as np
import scipp as sc

event_workspace = mantid.CreateSampleWorkspace(WorkspaceType='Event')
events = sc.compat.mantid.from_mantid(event_workspace)

# Works fine
mantid.Rebin(
    InputWorkspace=event_workspace,
    OutputWorkspace='histo',
    Params='2,-0.035,10')


edges = sc.Variable(
    ['tof'],
    values=np.geomspace(start=2, stop=10, num=100),
    unit=sc.units.us)
# Crash
histo = sc.rebin(events, 'tof', edges)
```

### PR DESCRIPTION
**Pull request by OwenArnold**
Fixes #1536 see script to emulate on the issue.

### CODE REVIEW

File: variable/rebin.cpp [hunk 1]
```diff
@@ -108,6 +108,10 @@ Variable rebin(const VariableConstView &var, const Dim dim,
     throw except::BinEdgeError(
         "The input does not have coordinates with bin-edges.");
 
+  if (is_bins(var))
+    throw except::BucketError("The input variable cannot be of type bins. Use "
+                              "bin or histogram instead of rebin.");
```
Comment (SimonHeybrock) [inline variable/rebin.cpp:113]: How do we want to refer to such variables? I think I have used "binned data" or "binned variables" in the docs, but I am not entirly happy about that?

Suggest to add quotes:

```suggestion
    throw except::BucketError("The input variable cannot be of type bins. Use "
                              "`bin` or `histogram` instead of `rebin`.");
```

File: variable/test/rebin_test.cpp [hunk 2]
```diff
@@ -224,3 +225,17 @@ TEST(Variable, rebin_mask_outer_single) {
...
+      makeVariable<double>(Dims{Dim::X}, Shape{4}, Values{1, 2, 3, 4});
+  Variable indices = makeVariable<std::pair<scipp::index, scipp::index>>(
+      dims, Values{std::pair{0, 3}});
+  Variable var = make_bins(indices, Dim::X, buffer);
+  const auto oldEdge =
+      makeVariable<double>(Dimensions{Dim::Y, 2}, Values{1, 4});
+  const auto newEdge =
+      makeVariable<double>(Dimensions{Dim::Y, 4}, Values{0, 1, 2, 3});
+  EXPECT_THROW([[maybe_unused]] auto res = rebin(var, Dim::Y, oldEdge, newEdge),
+               except::BucketError);
```
Comment (SimonHeybrock) [inline variable/test/rebin_test.cpp:240]: I think we should throw a `TypeError` instead? There is no problem with the buckets (bins), it is just a type not accepted by the function.

File: variable/rebin.cpp (hunk 1 above)
Comment (OwenArnold) [reply variable/rebin.cpp:113]: In the code comments `bin-variable` is used but I don't think that's a vast improvement. I'll open that question to the scipp channel.

Comment (SimonHeybrock) [reply variable/rebin.cpp:113]: Also a good discussion item for this afternoon.

File: variable/include/scipp/variable/bucket_variable.tcc [hunk 3]
```diff
@@ -106,10 +106,12 @@ public:
 template <class T> class BinVariableMaker : public BinVariableMakerCommon<T> {
 private:
   const VariableConstView
-  bucket_parent(const scipp::span<const VariableConstView> &parents) const {
+  bin_parent(const scipp::span<const VariableConstView> &parents) const {
+    if(parents.empty())
```
Comment (SimonHeybrock) [inline variable/include/scipp/variable/bucket_variable.tcc:110]: clang-format?

Hmm, it looks like our CI regex does not match `tcc`.

Comment (OwenArnold) [reply variable/include/scipp/variable/bucket_variable.tcc:110]: I'll update https://github.com/scipp/scipp/blob/master/.azure-pipelines/templates/code_quality_checks.yml#L22

**Review by SimonHeybrock — APPROVED** [review]

File: variable/include/scipp/variable/bucket_variable.tcc (hunk 3 above)
Comment (OwenArnold) [reply variable/include/scipp/variable/bucket_variable.tcc]: On second thoughts - applied fix to changed file here, but opening https://github.com/scipp/scipp/pull/1545 separately as will involve updating a number of unrelated tcc files I suspect.
