### PR TITLE
fix: add appropriate type combinations

### LINKED ISSUE #3176: Re-binning with float32 coords fails with unsupported dtype
Binning data first into a single bin, and subsequently re-binning with finer binning works fine with float64
```Py
import scipp as sc

table64 = sc.data.table_xyz(1000)
binned64 = table64.bin(x=1)
binned64.bin(x=10)
```
Screenshot at 2023-06-20 10-53-19

but doing the same with `float32` fails
```Py
table32 = sc.data.table_xyz(1000).to(dtype='float32')
for k, v in table32.coords.items():
    table32.coords[k] = v.to(dtype='float32')
table32
```
Screenshot at 2023-06-20 10-52-44
```Py
binned32 = table32.bin(x=1)
binned32.bin(x=10)
```
```
---------------------------------------------------------------------------
DTypeError                                Traceback (most recent call last)
Cell In [8], line 1
----> 1 binned.bin(x=10)

File ~/code/scipp/install/scipp/core/data_group.py:610, in data_group_overload.<locals>.impl(data, *args, **kwargs)
    608 if isinstance(data, DataGroup):
    609     return data.apply(impl, *args, **kwargs)
--> 610 return func(data, *args, **kwargs)

File ~/code/scipp/install/scipp/core/binning.py:582, in bin(x, arg_dict, **kwargs)
    580 edges = _make_edges(x, arg_dict, kwargs)
    581 erase = _find_replaced_dims(x, edges)
--> 582 return make_binned(x, edges=list(edges.values()), erase=erase)

File ~/code/scipp/install/scipp/core/binning.py:151, in make_binned(x, edges, groups, erase)
    149 if _can_operate_on_bins(x, edges, groups, erase):
    150     return combine_bins(x, edges=edges, groups=groups, dim=erase)
--> 151 return _cpp.bin(x, edges, groups, erase)

DTypeError: 'scipp.bin.begin_edge' does not support dtypes 'int64', 'int64', 'float32', 'span_const_float32', 
```

### PR DESCRIPTION
**Pull request by jokasimr**
Fixes #3176.

Is there a reason why `float` was excluded in the original `arg_list`?
Now I just added all type combinations between `double, float, int32_t, int64_t`.

### CODE REVIEW

File: lib/core/include/scipp/core/element/bin_detail.h [hunk 1]
```diff
@@ -16,9 +16,14 @@ using bin_range_arg =
...
-             bin_range_arg<int64_t, int64_t>, bin_range_arg<int32_t, int32_t>,
-             bin_range_arg<int32_t, double>,
+    arg_list<bin_range_arg<double, double>, bin_range_arg<double, float>,
+             bin_range_arg<double, int32_t>, bin_range_arg<double, int64_t>,
+             bin_range_arg<float, double>, bin_range_arg<float, float>,
+             bin_range_arg<float, int32_t>, bin_range_arg<float, int64_t>,
+             bin_range_arg<int32_t, double>, bin_range_arg<int32_t, float>,
+             bin_range_arg<int32_t, int32_t>, bin_range_arg<int32_t, int64_t>,
+             bin_range_arg<int64_t, double>, bin_range_arg<int64_t, float>,
+             bin_range_arg<int64_t, int32_t>, bin_range_arg<int64_t, int64_t>,
```
Comment (SimonHeybrock) [inline lib/core/include/scipp/core/element/bin_detail.h:26]: I think this is probably fine, but have you considered and checked if things can go wrong (such as comparisons) for certain type combinations, which might lead to, e.g., unintentionally dropping parts of the data?

**Review by SimonHeybrock — COMMENTED** [review]
> Is there a reason why float was excluded in the original arg_list?

No, just an oversight. Unfortunately Scipp's dtype handling mechanism requires being explicit about what is allowed. In many cases this is good, but we have also repeatedly run into "bugs" like these, where something that should work did not.

File: lib/core/include/scipp/core/element/bin_detail.h [hunk 2]
```diff
@@ -16,9 +16,14 @@ using bin_range_arg =
     std::tuple<scipp::index, scipp::index, Coord, scipp::span<const Edge>>;
 
 static constexpr auto bin_range_common = overloaded{
-    arg_list<bin_range_arg<double, double>, bin_range_arg<int64_t, double>,
-             bin_range_arg<int64_t, int64_t>, bin_range_arg<int32_t, int32_t>,
-             bin_range_arg<int32_t, double>,
+    arg_list<bin_range_arg<double, double>, bin_range_arg<double, float>,
```
[the remark this answers is not in the document]
Comment (jokasimr) [reply lib/core/include/scipp/core/element/bin_detail.h:19]: Added a `TYPED_TEST_SUITE`, it doesn't account for all combinations.

[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/core/include/scipp/core/element/bin_detail.h:19]: I don't think this is testing much: The `bin` algorithm is quite complex, calling a whole series of functions like this one. So in this case this test is mostly just "noise", since it provides no guarantee that the higher-level functionality works.

At a minimum, we should add a (Python) test that tests the full case reported in the linked issue.

File: src/scipp/data/__init__.py [hunk 3]
```diff
@@ -69,16 +69,22 @@ def vulcan_steel_strain_data() -> DataArray:
...
-    z = array(dims=['row'], unit='m', values=rng.random(nrow))
+    x = array(
+        dims=['row'], unit='m', values=rng.random(nrow) * coord_max, dtype=coord_dtype
+    )
+    y = array(
+        dims=['row'], unit='m', values=rng.random(nrow) * coord_max, dtype=coord_dtype
+    )
+    z = array(
+        dims=['row'], unit='m', values=rng.random(nrow) * coord_max, dtype=coord_dtype
+    )
```
Comment (SimonHeybrock) [inline src/scipp/data/__init__.py:87]: Not sure it matters much in practice, but now this function will be slower, even with the default `coord_max`. Unless you think this is more generally useful, maybe you can keep the scaling in the unit test where it is required?

Comment (jokasimr) [reply src/scipp/data/__init__.py]: I think it might be useful when testing with integer coordinates.
But I'll change it so it doesn't increase the runtime when used without scaling.

**Review by SimonHeybrock — APPROVED** [review]
