### PR TITLE
Fix exception in `bin` with edges along dim other than input dim

### LINKED ISSUE #2682: `bin` raises DimensionError when binning along new dimension with existing edges in attribute, such as result of `squeeze`
```python
import scipp as sc

da = sc.data.table_xyz(100).bin(x=10, y=1)
da = da.squeeze()
#del da.attrs['y']  # uncomment this line to make `bin` work again
da.bin(y=4)
```

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2682.

### CODE REVIEW

File: lib/dataset/bin.cpp [hunk 1]
```diff
@@ -294,11 +294,17 @@ class TargetBinBuilder {
...
               begin_edge(histogram ? left_edge(bin_coord) : bin_coord, key);
-          const auto end = histogram ? end_edge(right_edge(bin_coord), key)
-                                     : begin + 2 * units::none;
+          auto end = histogram ? end_edge(right_edge(bin_coord), key)
+                               : begin + 2 * units::none;
+          // When we have bin edges (of length 2) for a dimension that is not
+          // a dimension of the input it needs to be squeezed to avoid problems
+          // in various places later on.
+          begin = squeeze(begin, std::nullopt);
+          end = squeeze(end, std::nullopt);
```
Comment (jl-wynen) [inline lib/dataset/bin.cpp:307]: Can this cause problems when squeezing a dimension other than `dim`?

Comment (SimonHeybrock) [reply lib/dataset/bin.cpp:307]: I don't think so because `transform` will handle this equivalently. But given the overall code complexity and number of possible cases I cannot really guarantee that 100%.

Comment (jl-wynen) [reply lib/dataset/bin.cpp:307]: Can you add a test with a length=1 dimension but bin in a longer one?

**Review by jl-wynen — APPROVED** [review]
