### PR TITLE
Python operators and fixes

### LINKED ISSUE #482: Missing operations between `DataProxy` and `Variable`
For example:

```python
d['a'] += 1.2 * sc.units.m
```

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #482 (missing binaries in Python).

Also:
- missing `copy`.
- missing `__repr__`
- cleanup

### CODE REVIEW

File: core/dataset.cpp [hunk 1]
```diff
@@ -605,6 +605,16 @@ DataProxy DataProxy::operator/=(const DataConstProxy &other) const {
   return *this;
 }
 
+DataProxy DataProxy::operator+=(const Variable &other) const {
```
Comment (nvaytet) [inline core/dataset.cpp]: Strange that these were missing...
