### PR TITLE
Ensure Coords checked as part of setData

### LINKED ISSUE #295: Setting dense data for sparse item does not fail
`Dataset` is sensitive in some cases (though better than previous revision) to the order in which variables are applied during construction. A recent example to illustrate.

```
auto sparse_var = makeVariable<double>({Dim::Y, Dim::X}, {2, Dimensions::Sparse});
auto dense_var = makeVariable<double>({Dim::Y, Dim::X}, {2, 2});

Dataset a;
a.setData("dense_var", dense_var);
a.setSparseCoord("sparse_coord", sparse_var); // This throws

// Changing order bypasses checks
Dataset b;
b.setSparseCoord("sparse_coord", sparse_var);
b.setData("dense_var", dense_var); 
```

There may be other cases where we get temporal coupling issues. Should we consider adding some kind of indirection so that we can check all variables before attempting to make the dataset. Some kind of `builder` could be a solution. This would split out the construction parts of dataset, though we could make it look very similar to the current API.

### PR DESCRIPTION
**Pull request by OwenArnold**
Fixes #295 

**Do not merge until PR 298 merged**

### CODE REVIEW

File: core/dataset.cpp [hunk 1]
```diff
@@ -203,14 +224,38 @@ void Dataset::setAttr(const std::string &attrName, Variable attr) {
 /// (mismatching dtype, unit, or dimensions).
 void Dataset::setData(const std::string &name, Variable data) {
   setDims(data.dims());
+  const bool sparseData = data.dims().sparse();
+  if (m_data.count(name)) {
```
Comment (SimonHeybrock) [inline core/dataset.cpp]:
```cpp
if (contains(name) && operator[](name).dims().sparse() != sparseData)
  throw xyz;
```
saves 20 lines?

File: core/dataset.cpp [hunk 2]
```diff
@@ -268,7 +314,8 @@ DatasetConstProxy Dataset::slice(const Slice slice1,
 
 /// Return const slice of the dataset, sliced in three dimensions.
 ///
-/// This does not make a copy of the data. Instead of proxy object is returned.
+/// This does not make a copy of the data. Instead of proxy object is
+/// returned.
```
Comment (SimonHeybrock) [inline core/dataset.cpp]: formatting

File: core/dataset.cpp [hunk 3]
```diff
@@ -290,7 +337,8 @@ DatasetProxy Dataset::slice(const Slice slice1, const Slice slice2) & {
 
 /// Return slice of the dataset, sliced in three dimensions.
 ///
-/// This does not make a copy of the data. Instead of proxy object is returned.
+/// This does not make a copy of the data. Instead of proxy object is
+/// returned.
```
Comment (SimonHeybrock) [inline core/dataset.cpp]: formatting

File: core/dataset.cpp [hunk 4]
```diff
@@ -635,11 +683,12 @@ auto &apply(const Op &op, A &a, const B &b) {
 template <class Op, class A, class B>
 decltype(auto) apply_with_delay(const Op &op, A &&a, const B &b) {
   // For `b` referencing data in `a` we delay operation. The alternative would
-  // be to make a deep copy of `other` before starting the iteration over items.
+  // be to make a deep copy of `other` before starting the iteration over
+  // items.
```
Comment (SimonHeybrock) [inline core/dataset.cpp]: formatting

File: core/dataset.cpp [hunk 5]
```diff
@@ -635,11 +683,12 @@ auto &apply(const Op &op, A &a, const B &b) {
...
   std::optional<std::string_view> delayed;
-  // Note the inefficiency here: We are comparing some or all of the coords and
-  // labels for each item. This could be improved by implementing the operations
-  // for detail::DatasetData instead of DataProxy.
+  // Note the inefficiency here: We are comparing some or all of the coords
+  // and labels for each item. This could be improved by implementing the
+  // operations for detail::DatasetData instead of DataProxy.
```
Comment (SimonHeybrock) [inline core/dataset.cpp]: formatting

File: core/test/dataset_test.cpp [hunk 6]
```diff
@@ -260,10 +260,11 @@ TEST(DatasetTest, set_dense_data_with_sparse_coord) {
   ASSERT_THROW(a.setSparseCoord("sparse_coord_and_val", sparse_variable),
                std::runtime_error);
 
-  // Characterise temporal coupling issue below.
+  // Setting coords first yields same response.
   Dataset b;
   b.setSparseCoord("sparse_coord_and_val", sparse_variable);
-  b.setData("sparse_coord_and_val", dense_variable);
+  ASSERT_THROW(b.setData("sparse_coord_and_val", dense_variable),
+               std::runtime_error);
```
Comment (SimonHeybrock) [inline core/test/dataset_test.cpp]: I suggest throwing something like `except::SparseDimensionError`, or at least `except::DimensionError` with custom text.
