### PR TITLE
Binned op checks

### LINKED ISSUE #1678: Binary operations between two binned variables ignore buffer metadata
```python
import scipp as sc
import numpy as np
times = sc.Variable(dims=['event'], values=[0,1,3,1,1,1,4,1,1,2,1,1], dtype=sc.dtype.float64)
weights = sc.Variable(dims=['event'], values=np.ones(12), dtype=sc.dtype.float64)
table = sc.DataArray(data=weights, coords={'time':times})
begin = sc.Variable(dims=['x'], values=[0,6,6,8])
end = sc.Variable(dims=['x'], values=[6,6,8,12])
var = sc.bins(begin=begin, end=end, dim='event', data=table)
a = sc.DataArray(data=var, coords={'x':sc.Variable(['x'], values=np.arange(4.0))})
table.coords['time'] *= 1.1 # different event time coord for b
var = sc.bins(begin=begin, end=end, dim='event', data=table)
b = sc.DataArray(data=var, coords={'x':sc.Variable(['x'], values=np.arange(4.0))})
a + b # should throw
```

The problem is that `transform` with binned data considers only the data column and ignores everything else. In practice an operation like the above is unlikely to be required, so we should first look for a simple solution that simply forbids this behavior (throw an exception if both operands have `dtype=bins<DataArray>`, even if coords would in principle match). This is crucially important, because `a + b` is a natural thing a user might try to combina event data. We would even run into this by simply using code that was originally written for dense data.

### LINKED ISSUE #1726: Operation between binned data with bin contents variable and data array falls back to bins contents of variable
Same example as in #1678, change `data=table` to `data=table.data` in *one* of the arguments. In one case results has dtype `VariableView`, in other case `DataArrayView`. It picks the wrong parent and drops the meta data in one case. It should not.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
- Fixes #1678.
- Fixes #1726.

### CODE REVIEW

File: dataset/test/binned_arithmetic_test.cpp [hunk 1]
```diff
@@ -4,6 +4,7 @@
 
 #include "scipp/dataset/bins.h"
 #include "scipp/dataset/dataset.h"
+#include "scipp/dataset/string.h"
```
Comment (OwenArnold) [inline dataset/test/binned_arithmetic_test.cpp:7]: Is there some "operator<<" requirement here?

File: dataset/test/binned_arithmetic_test.cpp [hunk 2]
```diff
@@ -45,5 +45,32 @@ TEST_F(BinnedArithmeticTest, modify_slice_inplace_var) {
...
+
+TEST_F(BinnedArithmeticTest, var_and_var) {
+  Variable binned = make_bins(indices, Dim::Event, var);
+  EXPECT_EQ(binned + binned, make_bins(indices, Dim::Event, var + var));
+}
+
+TEST_F(BinnedArithmeticTest, fail_array_and_array) {
+  const auto binned = make_bins(indices, Dim::Event, array);
+  // In principle the operation could be allowed in this case since the coords
+  // match, but at this point our implementation is no sophisticated enough to
```
Comment (OwenArnold) [inline dataset/test/binned_arithmetic_test.cpp:60]:
```suggestion
  // match, but at this point our implementation is not sophisticated enough to
```

File: dataset/test/binned_arithmetic_test.cpp [hunk 3]
```diff
@@ -45,5 +45,32 @@ TEST_F(BinnedArithmeticTest, modify_slice_inplace_var) {
...
+  EXPECT_THROW(binned + binned, except::BinnedDataError);
+}
+
+TEST_F(BinnedArithmeticTest, var_and_array) {
+  const auto expected_array = DataArray(var + var, {{Dim::X, var + var}});
+  Variable binned_var = make_bins(indices, Dim::Event, var);
+  Variable binned_arr = make_bins(indices, Dim::Event, array);
+  const auto var_arr = binned_var + binned_arr;
+  const auto arr_var = binned_arr + binned_var;
+  EXPECT_EQ(var_arr.dtype(), binned_arr.dtype());
```
Comment (OwenArnold) [inline dataset/test/binned_arithmetic_test.cpp:72]: A comment here along the lines of https://github.com/scipp/scipp/issues/1726 might be helpful

File: variable/include/scipp/variable/bin_variable.tcc [hunk 4]
```diff
@@ -108,11 +108,20 @@ template <class T> class BinVariableMaker : public BinVariableMakerCommon<T> {
...
+    const auto count = std::count_if(parents.begin(), parents.end(), is_bins);
+    if (count == 0)
       throw except::BinnedDataError("Bin cannot have zero parents");
-    return parents.front().dtype() == dtype<bucket<T>>
-               ? parents.front()
-               : bin_parent(parents.subspan(1));
+    if (!std::is_same_v<T, Variable> && count > 1)
+      throw except::BinnedDataError(
+          "Binary operations such as '+' with binned data are only supported "
+          "with dtype=VariableView, got dtype=DataArrayView or similar. See "
```
Comment (OwenArnold) [inline variable/include/scipp/variable/bin_variable.tcc:120]: 👍  Good info. Very minor: could you pass actual received dtype as arg rather than hardcoding?

File: variable/include/scipp/variable/bin_variable.tcc [hunk 5]
```diff
@@ -108,11 +108,20 @@ template <class T> class BinVariableMaker : public BinVariableMakerCommon<T> {
 private:
   const VariableConstView
   bin_parent(const scipp::span<const VariableConstView> &parents) const {
-    if (parents.empty())
+    constexpr auto is_bins = [](auto &x) {
+      return x.dtype() == dtype<bucket<T>>;
+    };
+    const auto count = std::count_if(parents.begin(), parents.end(), is_bins);
```
Comment (OwenArnold) [inline variable/include/scipp/variable/bin_variable.tcc:114]: Why count_if and not find_if? you can then store result and avoid calling `find_if` below?

**Review by OwenArnold — CHANGES_REQUESTED** [review]

File: dataset/test/binned_arithmetic_test.cpp (hunk 1 above)
Comment (SimonHeybrock) [reply dataset/test/binned_arithmetic_test.cpp:7]: Well, if a test fails it gets picked up by `gtest`, so yes and no?

File: variable/include/scipp/variable/bin_variable.tcc (hunk 5 above)
Comment (SimonHeybrock) [reply variable/include/scipp/variable/bin_variable.tcc:114]: I would need to call `find_if` twice then to check if there is a second occurence? Would be much more complicated code?

Comment (OwenArnold) [reply variable/include/scipp/variable/bin_variable.tcc:114]: Yes I see also checking count > 1

File: variable/variable_factory.cpp [hunk 6]
```diff
@@ -6,6 +6,30 @@
...
+                                   });
+      it != vars.end())
+    return it->dtype();
+  // Second pass: Find bucket<Variable> (or other)
+  if (const auto it =
+          std::find_if(vars.begin(), vars.end(),
+                       [](const auto &v) { return variable::is_bins(v); });
+      it != vars.end())
+    return it->dtype();
+  // Not binned data
```
Comment (OwenArnold) [inline variable/variable_factory.cpp:29]: Minor: Could maybe refactor this with a sepate function returning the dtype and taking lambda as arg.

Comment (SimonHeybrock) [reply variable/variable_factory.cpp:29]: I don't understand? You mean a wrapper for `std::find_if`? What do we gain from that? I suppose you mean something else?

File: dataset/variable_instantiate_bin_elements.cpp [hunk 7]
```diff
@@ -6,17 +6,17 @@
...
 #include "scipp/variable/string.h"
 
 namespace scipp::variable {
 
-INSTANTIATE_BUCKET_VARIABLE(DatasetView, bucket<Dataset>)
-INSTANTIATE_BUCKET_VARIABLE(DataArrayView, bucket<DataArray>)
-INSTANTIATE_BUCKET_VARIABLE(DataArrayView_observer, bucket<DataArrayView>)
-INSTANTIATE_BUCKET_VARIABLE(DataArrayConstView_observer,
-                            bucket<DataArrayConstView>)
+INSTANTIATE_BIN_VARIABLE(DatasetView, bucket<Dataset>)
```
Comment (OwenArnold) [inline dataset/variable_instantiate_bin_elements.cpp:15]: I guess we would later do a rename `bucket<Dataset>` -> `bin<Dataset>` or was there a reason to keep that type name?

File: variable/variable_factory.cpp (hunk 6 above)
Comment (OwenArnold) [reply variable/variable_factory.cpp:29]: Not a wrapper for `find_if`. I looks like you are extracting the bins dtype from a vector of VariableConstView. Only difference between first attempt and second pass is the lambda used. It probably wouldn't reduce the number of lines by extracting a separate function for this, so leave as is.

**Review by OwenArnold — APPROVED** [review]

File: dataset/variable_instantiate_bin_elements.cpp (hunk 7 above)
Comment (SimonHeybrock) [reply dataset/variable_instantiate_bin_elements.cpp:15]: Yes. It wasn't a quick fix since we have a function called `bin`, which is in conflict.
