### PR TITLE
fix: treat base is zero case specially

### LINKED ISSUE #3507: NaN result when applying non-integer power to scalar of 0 when variance is present
This is a bit of a weird one but:
Screenshot at 2024-08-02 10-41-32

The bug seems to happen when the value is 0 and a variance is present, and the power is non-integer.

### PR DESCRIPTION
**Pull request by jokasimr**
Fixes #3507 

I think most of the cases in the issue are fine except:
```python
sc.scalar(0.0, variance=0.0)**0.5
# and
sc.scalar(0.0, variance=1.0)**0.5
```
because in those cases the value of the result should just be `0.0` and not `nan`.

### CODE REVIEW

**Comment by jokasimr** [comment]
I wasn't able to locate where we test the values / variances of arithmetic operations.
Does anyone have a link to the file where it would be suitable to test this?

**Comment by SimonHeybrock** [comment]
> I wasn't able to locate where we test the values / variances of arithmetic operations. Does anyone have a link to the file where it would be suitable to test this?

These should generally all be here: https://github.com/scipp/scipp/blob/main/lib/core/test/value_and_variance_test.cpp

File: lib/core/include/scipp/core/value_and_variance.h [hunk 1]
```diff
@@ -71,8 +71,10 @@ template <class B, class E>
 constexpr auto pow(const ValueAndVariance<B> base, const E exponent) noexcept {
   const auto pow_1 = numeric::pow(base.value, exponent - 1);
   const auto var_factor = std::abs(exponent) * pow_1;
-  return ValueAndVariance{pow_1 * base.value,
-                          var_factor * var_factor * base.variance};
+  const auto pow_0 = (base.value == 0 && exponent >= 0 && exponent < 1)
+                         ? 0
```
Comment (SimonHeybrock) [inline lib/core/include/scipp/core/value_and_variance.h:75]: - Shouldn't 0**0 give 1?
- Why do we need the `exponent < 1`, or the sign check? Isn't it just zero everywhere if the base is zero (except of the exponent also is)?

Comment (jokasimr) [reply lib/core/include/scipp/core/value_and_variance.h:75]: 1. Good catch.
2. Yeah that's probably right, it's an unnecessary check.

**Review by SimonHeybrock — APPROVED** [review]
