### PR TITLE
DataArray operation fixes and additions

### LINKED ISSUE #873: DataArray in-place operations do not handle masks
For example, `DataProxy::operator+=` treats masks, but `DataArray::operator+=` does not. Probably the latter should just forward to the former?

### PR DESCRIPTION
**Pull request by SimonHeybrock**
- Fix missing mask handling. Fixes #873.
- Add missing support for `sparse *= histogram` and `sparse /= histogram`. Fixes #873.
- Fix tests to exercise masking. Previously the dataset factory returned the same masks in every call.
- Fix tests to create correct reference.

### CODE REVIEW

File: core/data_array.cpp [hunk 1]
```diff
@@ -113,26 +118,55 @@ Variable sparse_dense_op_impl(Op op, const VariableConstProxy &sparseCoord_,
...
   return *this;
 }
 
+template <class Op>
+DataArray &sparse_dense_op_inplace(Op op, DataArray &a,
+                                   const DataConstProxy &b) {
+  if (!is_sparse_and_histogram(a, b)) {
+    expect::coordsAndLabelsAreSuperset(a, b);
+    union_or_in_place(a.masks(), b.masks());
+    std::is_same_v<Op, std::decay_t<decltype(times)>> ? a.data() *= b.data()
```
Comment (OwenArnold) [inline core/data_array.cpp]: This seems to imply that template arg `Op` is either times or divide. i.e could be misused for other operation arguments - would it be better to redefine `times` and `divide` to be structs that could provide the operators required by this function?

File: core/data_array.cpp [hunk 2]
```diff
@@ -113,26 +133,54 @@ Variable sparse_dense_op_impl(Op op, const VariableConstProxy &sparseCoord_,
...
   return *this;
 }
 
+template <class Op>
+DataArray &sparse_dense_op_inplace(Op op, DataArray &a,
+                                   const DataConstProxy &b) {
+  if (!is_sparse_and_histogram(a, b)) {
+    expect::coordsAndLabelsAreSuperset(a, b);
+    union_or_in_place(a.masks(), b.masks());
+    op.inplace(a.data(), b.data());
```
Comment (OwenArnold) [inline core/data_array.cpp]: 👍
