### PR TITLE
Replace std::unordered_map with custom Dict class

### LINKED ISSUE #2696: Deleting from Dict while iterating segfaults
This code segfaults:
```.py
import scipp as sc
da = sc.DataArray(sc.scalar(3),
                  attrs={'a': sc.scalar(1),
                         'b': sc.scalar(2),})
for k in da.attrs:
    del da.attrs[k]
```

The operation cannot really be allowed and using a Python dict instead is unreliable as well (might work or might raise an exception). But we should raise instead of crash.

Specifically, it looks like the iterator itself causes the segfault after the first deletion. It thinly wraps a `boost::transform_iterator` (observed the same with `da.attrs.items()` which uses `std::unordered_map::iterator`). So we are probably dealing with dangling pointer. Detecting / avoiding them could turn out very complicated.

### PR DESCRIPTION
**Pull request by jl-wynen**
Fixes #2696

Also removed the need for `boost::transform_iterator` in all but one places.

Also guarantee that coords, attrs, masks, dataset items are stored and iterated in the order of insertion. I am not sure if we should promise that or keep it as an implementation detail. So there are no release notes. What do you think?

### CODE REVIEW

**Comment by jl-wynen** [comment]
Pushed to check if the CI builds are fixed. Going to add more tests.

**Comment by jl-wynen** [comment]
Ready for review

**Review by SimonHeybrock — COMMENTED** [review]
Comments so far (did not look at iterator details and `dict_test.cpp` yet):

File: lib/core/include/scipp/core/dict.h [hunk 1]
```diff
@@ -0,0 +1,405 @@
...
+      typename dict_detail::IteratorType<const Keys,
+                                         typename Keys::const_iterator,
+                                         typename Values::const_iterator>::type;
+
+  Dict(std::initializer_list<std::pair<const Key, Value>> items) {
+    reserve(items.size());
+    for (const auto &[key, value] : items) {
+      insert_or_assign(key, value);
+    }
+  }
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:254]: Not sure what is a good solution. `std::unordered_map` seems to use `insert` and drop all but the first occurrence of a key. Would you rather use that?
This constructor is only used in tests. In all other cases, dicts are built by calling `insert_of_assign` directly.

File: lib/dataset/include/scipp/dataset/aligned_dict.h [hunk 2]
```diff
@@ -4,45 +4,23 @@
...
-auto slice_map(const Sizes &sizes, const T &map, const Slice &params) {
-  T out;
+template <class Mapping>
+Mapping slice_map(const Sizes &sizes, const Mapping &map, const Slice &params) {
+  Mapping out;
   for (const auto &[key, value] : map) {
     if (value.dims().contains(params.dim())) {
       if (value.dims()[params.dim()] == sizes[params.dim()]) {
-        out[key] = value.slice(params);
+        out.insert_or_assign(key, value.slice(params));
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/dataset/include/scipp/dataset/aligned_dict.h:23]: But insert silently does nothing if the key already exists. Is this really better?

File: lib/dataset/include/scipp/dataset/aligned_dict.h [hunk 3]
```diff
@@ -52,38 +30,40 @@ auto slice_map(const Sizes &sizes, const T &map, const Slice &params) {
...
-      out[key] = value.as_const();
+      out.insert_or_assign(key, value.as_const());
     }
   }
   return out;
 }
 
 /// Common functionality for other const-view classes.
-template <class Key, class Value> class Dict {
+template <class Key, class Value> class AlignedDict {
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/dataset/include/scipp/dataset/aligned_dict.h:46]: Yes. Better ideas are welcome!

File: lib/dataset/aligned_dict.cpp [hunk 4]
```diff
@@ -69,43 +74,44 @@ bool equals_nan(const Dict<Key, Value> &a, const Dict<Key, Value> &b) {
...
   return at(key);
 }
 
 /// Const reference to the coordinate for given dimension.
 template <class Key, class Value>
-const Value &Dict<Key, Value>::at(const Key &key) const {
+const Value &AlignedDict<Key, Value>::at(const Key &key) const {
   scipp::expect::contains(*this, key);
-  return m_items.at(key);
+  return m_items[key];
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/dataset/aligned_dict.cpp:103]: Too lazy to implement `Dict::at`. But I can add it for completeness.

File: lib/core/include/scipp/core/dict.h [hunk 5]
```diff
@@ -0,0 +1,405 @@
...
+
+  decltype(auto) operator->() const {
+    using Result = typename BaseIterator::template TemporaryItem<
+        std::decay_t<decltype(**this)>>;
+    return Result(**this);
+  }
+
+private:
+  // mutable to support stateful function objects that change their state.
+  mutable std::decay_t<Func> m_func;
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:177]: Seems to not be required for our current use cases.

File: lib/core/include/scipp/core/dict.h [hunk 6]
```diff
@@ -0,0 +1,405 @@
...
+      insert_or_assign(key, value);
+    }
+  }
+
+  Dict() = default;
+  ~Dict() noexcept = default;
+  Dict(const Dict &other) = default;
+  Dict(Dict &&other) noexcept = default;
+  Dict &operator=(const Dict &other) = default;
+  Dict &operator=(Dict &&other) noexcept = default;
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:261]: We don't (except for default ctor). But I like being explicit.

File: lib/core/include/scipp/core/dict.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/core/include/scipp/core/dict.h:254]: Can we throw?

File: lib/dataset/include/scipp/dataset/aligned_dict.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/dataset/include/scipp/dataset/aligned_dict.h:46]: `ShapedDict`? `DimensionedDict`?

File: lib/dataset/aligned_dict.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/dataset/aligned_dict.cpp:103]: Hmm, I thought I saw it above?

File: lib/core/include/scipp/core/dict.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/core/include/scipp/core/dict.h:261]: Seems like a source of bugs?

File: lib/core/include/scipp/core/dict.h [hunk 7]
```diff
@@ -0,0 +1,405 @@
...
+  Iterator &operator=(Iterator &&other) noexcept = default;
+  ~Iterator() noexcept = default;
+
+  decltype(auto) operator*() const {
+    expect_container_unchanged();
+    if constexpr (sizeof...(IteratorIndices) == 1) {
+      return *std::get<0>(m_iterators);
+    } else {
+      return std::make_pair(std::cref(*std::get<0>(m_iterators)),
+                            std::ref(*std::get<1>(m_iterators)));
```
Comment (SimonHeybrock) [inline lib/core/include/scipp/core/dict.h:71]: Remind me: I think we had decided that ideally we want to return `std::pair<const Key, Value> &`. But we cannot *store* `std::pair<const Key, Value>`. Can we return the former if we have the latter? If I remember correctly it is not? Can we force it using a cast?

File: lib/core/include/scipp/core/dict.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/core/include/scipp/core/dict.h:177]: Remove then?

File: lib/dataset/aligned_dict.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/dataset/aligned_dict.cpp:103]: I double checked, it is implemented already.

File: lib/dataset/aligned_dict.cpp [hunk 8]
```diff
@@ -193,71 +199,71 @@ void Dict<Key, Value>::set(const key_type &key, mapped_type coord) {
...
 }
 
 template <class Key, class Value>
-Value Dict<Key, Value>::extract(const key_type &key) {
-  auto extracted = at(key);
-  erase(key);
-  return extracted;
+Value AlignedDict<Key, Value>::extract(const key_type &key) {
+  expect_writable(*this);
+  return m_items.extract(key);
```
Comment (SimonHeybrock) [inline lib/dataset/aligned_dict.cpp:211]: Why `scipp::expect::contains` in one case but not the other? Will the exceptions be inconsistent?

File: lib/dataset/aligned_dict.cpp [hunk 9]
```diff
@@ -280,38 +287,38 @@ Dict<Key, Value> &Dict<Key, Value>::setSlice(const Slice &s, const Dict &dict) {
...
-void Dict<Key, Value>::rename(const Dim from, const Dim to) {
+void AlignedDict<Key, Value>::rename(const Dim from, const Dim to) {
   m_sizes.replace_key(from, to);
-  for (auto &item : m_items)
-    if (item.second.dims().contains(from))
-      item.second.rename(from, to);
+  for (auto it = m_items.values_begin(); it != m_items.values_end(); ++it)
+    if ((*it).dims().contains(from))
+      (*it).rename(from, to);
 }
```
Comment (SimonHeybrock) [inline lib/dataset/aligned_dict.cpp:295]: This comment is about the Python `rename` method, which is *not* the same as this (this method here is just doing the equivalent of `rename_dims`, which is also used to implemented `rename`):

https://github.com/scipp/scipp/blob/5f9d8256dfa6251808f5a7d226177fbda075dc52/src/scipp/core/dimensions.py#L132

does not preserve insertion order: The renamed coords will be moved to the end. Is that what we want to do? Or do we want to be able to rename keys without changing the order?

File: lib/dataset/aligned_dict.cpp [hunk 10]
```diff
@@ -330,27 +337,56 @@ Dict<Key, Value> Dict<Key, Value>::merge_from(const Dict &other) const {
...
 
 template <class Key, class Value>
-bool Dict<Key, Value>::item_applies_to(const Key &key,
-                                       const Dimensions &dims) const {
-  const auto &val = m_items.at(key);
+bool AlignedDict<Key, Value>::item_applies_to(const Key &key,
+                                              const Dimensions &dims) const {
+  const auto &val = m_items[key];
```
Comment (SimonHeybrock) [inline lib/dataset/aligned_dict.cpp:342]: I would prefer keeping the `at`: It makes it clear to the reader that this will *not* result in insertion, even if they don't know that the map being used is a special implementation.

File: lib/dataset/aligned_dict.cpp [hunk 11]
```diff
@@ -330,27 +337,56 @@ Dict<Key, Value> Dict<Key, Value>::merge_from(const Dict &other) const {
...
-                                              const Dict<Dim, Variable> &b);
-template SCIPP_DATASET_EXPORT bool
-equals_nan(const Dict<std::string, Variable> &a,
-           const Dict<std::string, Variable> &b);
+template <class Key, class Value>
+core::Dict<Key, Value> union_(const AlignedDict<Key, Value> &a,
+                              const AlignedDict<Key, Value> &b,
+                              std::string_view opname) {
+  core::Dict<Key, Value> out;
+  out.reserve(out.size() + b.size());
```
Comment (SimonHeybrock) [inline lib/dataset/aligned_dict.cpp:360]: Reserving too much in most cases, but probably does not matter?

File: lib/dataset/aligned_dict.cpp [hunk 12]
```diff
@@ -330,27 +337,56 @@ Dict<Key, Value> Dict<Key, Value>::merge_from(const Dict &other) const {
...
+      out.insert_or_assign(key, val);
+  }
+  return out;
+}
+
+template <class Key, class Value>
+core::Dict<Key, Value> intersection(const AlignedDict<Key, Value> &a,
+                                    const AlignedDict<Key, Value> &b) {
+  core::Dict<Key, Value> out;
+  out.reserve(a.size());
```
Comment (SimonHeybrock) [inline lib/dataset/aligned_dict.cpp:376]: Reserving way too much in many cases: Typical cases might have `a` (from neutron data array) with 300 attrs and `b` (from neutron monitor data array) with no/few attrs. Just don't reserve here?

File: lib/dataset/include/scipp/dataset/aligned_dict.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/dataset/include/scipp/dataset/aligned_dict.h:23]: I am wondering if our C++ naming should mirror Python naming in more cases, e.g., call it `setitem`? Not a request to change here, just pondering...

File: lib/core/test/dict_test.cpp [hunk 13]
```diff
@@ -0,0 +1,557 @@
...
+  dict.reserve(1);
+  dict.insert_or_assign(Dim::X, 719);
+  auto it = dict.keys_begin();
+  dict.reserve(16);
+  EXPECT_THROW_DISCARD(*it, std::runtime_error);
+  EXPECT_THROW_DISCARD(++it, std::runtime_error);
+  EXPECT_THROW_DISCARD(it == dict.keys_end(), std::runtime_error);
+}
+
+TEST(Dict, key_iterator_throws_if_element_inserted_with_realloc) {
```
Comment (SimonHeybrock) [inline lib/core/test/dict_test.cpp:209]: 👍

File: lib/core/test/dict_test.cpp [hunk 14]
```diff
@@ -0,0 +1,557 @@
...
+  EXPECT_EQ(*it, 61892);
+  ++it;
+  EXPECT_EQ(*it, 619);
+  ++it;
+  EXPECT_EQ(it, dict.values_end());
+}
+
+TEST(Dict, const_value_iterator_produces_correct_values) {
+  DimDict dict{{Dim::Time, 4561}, {Dim::Event, 76}};
+  // NOLINTNEXTLINE(performance-unnecessary-copy-initialization)
```
Comment (SimonHeybrock) [inline lib/core/test/dict_test.cpp:308]: Can we globally disable all "performance" linting within the `test/` subfolders?

File: lib/core/test/dict_test.cpp [hunk 15]
```diff
@@ -0,0 +1,557 @@
...
+  EXPECT_EQ(it->second, 619);
+  ++it;
+  EXPECT_EQ(it, dict.end());
+}
+
+TEST(Dict, iterator_can_change_values) {
+  DimDict dict{{Dim::Position, -51}, {Dim::Row, 827}};
+  auto it = dict.begin();
+  (*it).second = 991;       // cppcheck-suppress unreadVariable
+  (*(++it)).second = -9761; // cppcheck-suppress unreadVariable
```
Comment (SimonHeybrock) [inline lib/core/test/dict_test.cpp:360]: This cppcheck warning is annoying and reoccuring (had similar issue with assigning to view element recently). Why can it not understand  what iterators are? Having to suppress this everywhere is not ideal.

File: lib/dataset/aligned_dict.cpp (hunk 9 above)
Comment (SimonHeybrock) [reply lib/dataset/aligned_dict.cpp:295]: As part of fixing #2734 I will be changing the C++ `rename` methods.

File: lib/dataset/dataset.cpp [hunk 16]
```diff
@@ -146,41 +147,35 @@ void Dataset::setData(const std::string &name, Variable data,
 /// dataset. Throws if there are existing but mismatching coords, masks, or
 /// attributes. Throws if the provided data brings the dataset into an
 /// inconsistent state (mismatching dimensions).
-void Dataset::setData(const std::string &name, const DataArray &data) {
+void Dataset::setData(const std::string &name, DataArray data) {
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/dataset/dataset.cpp:150]: No, the previous version pretended to move components of `data` into the dataset. But it didn't actually work because `data` was const. So it triggered copies.
I tried to switch to a copy-and-move idiom but lost a `move` for setting the data.

File: lib/dataset/include/scipp/dataset/aligned_dict.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/dataset/include/scipp/dataset/aligned_dict.h:23]: This PR tries to match a Python dict as closely as possible. So it would make sense to match its naming. Should we do a pass over several types (at least Dict, AlignedDict, Dataset) to change to Python names? As you said, this can be done later.

File: lib/core/include/scipp/core/dict.h (hunk 7 above)
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:71]: > Can we return the former if we have the latter?

Yes. But we cannot store it because `std::vector` needs to move its elements (at the very least in `erase`) which requires non-const types.

> Can we force it using a cast?

I guess with a `reinterpret_cast`. But I don't know if this can have bad side-effects.

File: lib/dataset/aligned_dict.cpp (hunk 8 above)
Comment (jl-wynen) [reply lib/dataset/aligned_dict.cpp:211]: What do you mean? The function with a default value calls `AlignedDict::contains` and uses `extract` without default arg to do the extraction.

File: lib/dataset/aligned_dict.cpp (hunk 9 above)
Comment (jl-wynen) [reply lib/dataset/aligned_dict.cpp:295]: I think we should preserve the order. We can implement it entirely in this class. But I'm going to wait for your changes.

File: lib/dataset/aligned_dict.cpp (hunk 10 above)
Comment (jl-wynen) [reply lib/dataset/aligned_dict.cpp:342]: Assuming that we keep the C++ naming convention. If we switch to Python names, should we remove `at`?

File: lib/dataset/aligned_dict.cpp (hunk 11 above)
Comment (jl-wynen) [reply lib/dataset/aligned_dict.cpp:360]: It shouldn't matter. If we reserve too little, it will grow geometrically and overallocate anyway.

File: lib/core/test/dict_test.cpp (hunk 14 above)
Comment (jl-wynen) [reply lib/core/test/dict_test.cpp:308]: Makes sense

File: lib/core/test/dict_test.cpp (hunk 15 above)
Comment (jl-wynen) [reply lib/core/test/dict_test.cpp:360]: This is probably difficult to do. It needs to understand the relationship between the iterator, the dict, and the temporary pair of references.

File: lib/dataset/aligned_dict.cpp (hunk 8 above)
Comment (SimonHeybrock) [reply lib/dataset/aligned_dict.cpp]: `erase` calls `scipp::expect::contains(*this, key);` but `extract` does not. Why?

File: lib/dataset/aligned_dict.cpp (hunk 9 above)
Comment (SimonHeybrock) [reply lib/dataset/aligned_dict.cpp]: See #2775. I think the new implementation should automatically preserve order once the new dict is used.

File: lib/dataset/aligned_dict.cpp (hunk 10 above)
Comment (SimonHeybrock) [reply lib/dataset/aligned_dict.cpp]: I think we should keep naming from `std` at least for std-like containers?

File: lib/dataset/include/scipp/dataset/aligned_dict.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/dataset/include/scipp/dataset/aligned_dict.h]: I think `Dict` should maybe stick to the C++ naming, since it is meant as a (nearly) drop-in replacement for a C++ map. But everything that we bind to Python (such as instances of `AlignedDict`) would be a candidate for a rename?

[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/dataset/include/scipp/dataset/aligned_dict.h]: I would keep `Dict` and `SizedDict` (renamed) consistent with each other.

File: lib/dataset/aligned_dict.cpp (hunk 8 above)
Comment (jl-wynen) [reply lib/dataset/aligned_dict.cpp]: An oversight. I changed it such that `SizedDict` no longer checks anything. It is all handled by `Dict`. But unfortunately, that means that `dict_keys_to_string` needs to be defined in `dict.h`

File: lib/dataset/aligned_dict.cpp (hunk 9 above)
Comment (jl-wynen) [reply lib/dataset/aligned_dict.cpp]: It doesn't because it didn't touch `rename`. We still pop a coord and append it at the end.

File: lib/core/include/scipp/core/dict.h [hunk 17]
```diff
@@ -0,0 +1,423 @@
...
+  [[nodiscard]] auto begin() noexcept {
+    return iterator(m_keys, m_keys.cbegin(), m_values.begin());
+  }
+
+  [[nodiscard]] auto end() noexcept {
+    return iterator(m_keys, m_keys.cend(), m_values.end());
+  }
+
+  [[nodiscard]] auto begin() const noexcept {
+    return const_iterator(m_keys, m_keys.cbegin(), m_values.begin());
```
Comment (SimonHeybrock) [inline lib/core/include/scipp/core/dict.h:371]:
```suggestion
    return const_iterator(m_keys, m_keys.cbegin(), m_values.cbegin());
```
? Probably the same since `const_iterator` is used, but helps readability. Same below and above.

File: lib/core/include/scipp/core/dict.h [hunk 18]
```diff
@@ -0,0 +1,423 @@
...
+  }
+
+  scipp::index expect_find_index(const Key &key) const {
+    return index_of(expect_find_key(key));
+  }
+};
+
+template <class Mapping>
+std::string dict_keys_to_string(const Mapping &dict,
+                                const std::string_view dict_name = "Dict") {
```
Comment (SimonHeybrock) [inline lib/core/include/scipp/core/dict.h:407]: Can we move this to a `cpp` file? I don't like including `sstream` everywhere. Probably needs a signature change then, e.g., to `span<Key>` so we can instantiate it.

File: lib/core/test/dict_test.cpp [hunk 19]
```diff
@@ -0,0 +1,538 @@
...
+
+#include "scipp/core/dict.h"
+#include "scipp/units/dim.h"
+
+#include "test_macros.h"
+
+using namespace scipp::core;
+using scipp::Dim;
+
+using DimDict = Dict<Dim, int>;
```
Comment (SimonHeybrock) [inline lib/core/test/dict_test.cpp:14]: There are a bunch of places that use `std::move` on the values of the dict, is it worth testing with a `Value` that has a non-trivial `move`, such as `std::string`?

File: lib/dataset/test/coords_view_test.cpp [hunk 20]
```diff
@@ -1,5 +1,6 @@
 // SPDX-License-Identifier: BSD-3-Clause
 // Copyright (c) 2022 Scipp contributors (https://github.com/scipp)
+#include <gmock/gmock.h>
```
Comment (SimonHeybrock) [inline lib/dataset/test/coords_view_test.cpp:3]: Used for...?

**Review by SimonHeybrock — COMMENTED** [review]
I had another close look, and I think I am nearly happy with this. Nice work!

A couple more questions and comments:

File: lib/core/include/scipp/core/dict.h [hunk 21]
```diff
@@ -0,0 +1,423 @@
...
+    auto *operator->() { return &m_item; }
+
+  private:
+    std::decay_t<T> m_item;
+  };
+
+private:
+  using IteratorStorage =
+      std::tuple<typename std::tuple_element<IteratorIndices,
+                                             std::tuple<It1, It2>>::type...>;
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:138]: The reason was that I wanted to avoid doing something like
```.cpp
++std::get<0>(m_iterators);
if constexpr(sizeof...(It) == 2)
  ++std::get<1>(m_iterators);
```
in every function. But looking at it now, `operator++` is the only one that actually uses `IteratorIndices`. So I can just remove the indices and use the code shown above.

File: lib/core/include/scipp/core/dict.h [hunk 22]
```diff
@@ -0,0 +1,423 @@
...
+
+  IteratorStorage m_iterators;
+  std::reference_wrapper<Container> m_container;
+  const void *m_end_address;
+
+  void expect_container_unchanged() const {
+    if (m_container.get().data() + m_container.get().size() != m_end_address) {
+      throw std::runtime_error("dictionary changed size during iteration");
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:146]: How would this cause a problem? Suppose we have a length=1 vector when we create the iterator and suppose `data()` is 0x10. Then, `m_end_address = data() + size() = 0x11`. When the element is erased, there are multiple possible outcomes:
- `data` returns null -> `data() + size() = 0x00 + 0 = 0x00 != m_end_address`
- `data` returns the previous base address -> `data() + size() = 0x10 + 0 = 0x10 != m_end_address`
- `data` returns the previous end address -> `data() + size() = 0x11 + 0 = 0x11 = m_end_address` This case would cause a problem. But is there any real risk that this will happen?

Or the other way around. Suppose we start with an empty vector and add an element:
- `data` of empty returns 0x00 -> after push: `data() + size() = 0x10 + 1 = 0x11 != m_end_address`
- `data` of empty returns 0x11 -> after push: `data() + size() = 0x10 + 1 = 0x11 = m_end_address` This would require the pointer of empty to start one byte after the location where memory will be allocated. This will never happen in practice unless std::vector can see the future.

If there is a special allocator, e.g. using a memory pool, then there could be problems because a vector might reallocate and end up in the same spot. But do we need to worry about this?

File: lib/core/include/scipp/core/dict.h [hunk 23]
```diff
@@ -0,0 +1,423 @@
...
+      m_values[index_of(key_it)] = std::forward<V>(value);
+    }
+  }
+
+  void erase(const key_type &key) { static_cast<void>(extract(key)); }
+
+  mapped_type extract(const key_type &key) {
+    const auto key_it = expect_find_key(key);
+    m_keys.erase(key_it);
+    const auto value_it = std::next(m_values.begin(), index_of(key_it));
```
[the remark this answers is not in the document]
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:295]: I think it just uses pointer arithmetic and safe. But yes, it is better to swap.

File: lib/core/include/scipp/core/dict.h (hunk 17 above)
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:371]: Below, yes. Above, no. The non-const `begin` and `end` need to return `m_keys.cbegin()` but `m_values.begin()` (same with end).

File: lib/core/include/scipp/core/dict.h (hunk 18 above)
Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h:407]: This would require knowing all possible key types ahead of time. Do we want to lock us in like that?

File: lib/core/include/scipp/core/dict.h (hunk 22 above)
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/core/include/scipp/core/dict.h:146]: > But is there any real risk that this will happen?

I don't know, is there a reason to take any chances? The extra pointer comparison would not add any real overhead, would it?

> If there is a special allocator, e.g. using a memory pool, then there could be problems because a vector might reallocate and end up in the same spot. But do we need to worry about this?

Yes, absolutely! The allocators used by the standard libraries have become quite advanced. For example, as far as I know gcc's allocator now includes many things that `tcmalloc` used to do, by default.

File: lib/core/test/dict_test.cpp (hunk 19 above)
Comment (jl-wynen) [reply lib/core/test/dict_test.cpp:14]: Good point. But `std::string` is not the best choice because its move might be trivial. I'm going to use a custom type that holds an int behind a pointer.

File: lib/dataset/test/coords_view_test.cpp (hunk 20 above)
Comment (jl-wynen) [reply lib/dataset/test/coords_view_test.cpp:3]: Forgot to remove. I tried to use a container matcher in the new test but it doesn't like our dict.

File: lib/core/include/scipp/core/dict.h (hunk 18 above)
Comment (SimonHeybrock) [reply lib/core/include/scipp/core/dict.h:407]: We know all possible key types. There are just two. If you are really worried, but it into a `tcc` file which potential user users can include in their `cpp`.

Comment (jl-wynen) [reply lib/core/include/scipp/core/dict.h]: Done. It is a bit tricky because `dict_keys_to_string` needs `Dict` and vice versa. So `dict_keys_to_string` is now implemented in `dict.cpp` and not `string.cpp`.

**Review by SimonHeybrock — APPROVED** [review]
