### PR TITLE
Fix serious bug in `bin`

### LINKED ISSUE #2679: Broken `bin`?
```python
import scipp as sc
table = sc.data.table_xyz(nrow=9_000_000)
table.data = sc.ones(sizes=table.sizes, dtype='float32')
da = table.bin(x=70000)
```

Now consider `da.bins.constituents['data']` (or coords). It appears to contain zeros?

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2679.

### CODE REVIEW

File: lib/core/include/scipp/core/element/map_to_bins.h [hunk 1]
```diff
@@ -62,7 +62,7 @@ auto map_to_bins_chunkwise = [](auto &binned, auto &bins, const auto &data,
       const auto i_bin = bin_indices[i];
       if (i_bin < 0)
         continue;
-      const uint8_t j = i_bin % chunksize;
```
Comment (nvaytet) [inline lib/core/include/scipp/core/element/map_to_bins.h:65]: Just for my understanding, why were we only seeing the bug for number of bins larger than > 65536 if the range of `uint8_t` is much smaller?
Also, why is `InnerIndex` `uint16_t` instead of `int16_t`?

Comment (SimonHeybrock) [reply lib/core/include/scipp/core/element/map_to_bins.h:65]: `chunksize` was set as `128` for less than `128**2` bins, `256` for less than 256**2` bins, etc.

Comment (SimonHeybrock) [reply lib/core/include/scipp/core/element/map_to_bins.h:65]: You mean `int16_t` instead of `uint16_t`? Since `int16_t` is large enough for our needs there is no reason for risky mixing of signed and unsigned integer arithmetic.

Comment (nvaytet) [reply lib/core/include/scipp/core/element/map_to_bins.h:65]: ok thanks!

**Review by nvaytet — APPROVED** [review]
Looks good to me, but maybe you also want @jl-wynen to have a look.

Is this one of those cases where we should be making patch releases for scipp 0.12-0.14 ?

**Comment by SimonHeybrock** [comment]
> Is this one of those cases where we should be making patch releases for scipp 0.12-0.14 ?

Worth considering... and I think in doing so I found yet another problem with our release process: Making a release writes to the top-level docs (in addition to the one in the release's folder). That is we cannot really make a release except for the latest version (at least not without fixing things up later again). This is probably a good reason to go ahead with #2606, and change the release to either (a) not deploy any docs at all, or (b) deploy only to the release folder.
