### PR TITLE
Fix `nanmean` for `vector3` dtype

### LINKED ISSUE #2579: `isnan` broken for spatial dtypes such as `vector3`
This always gives `false` for, e.g., `Eigen::Vector3d`. Therefore `nanmean` is broken in that case (returns the same as `mean`, i.e., will contains NAN.

The bug is in https://github.com/scipp/scipp/blob/701dd15d8fab49b31d8d9de618ea88042562811f/lib/common/include/scipp/common/numeric.h#L102-L105.

Note that a similar issue is present for `isinf` and possibly more.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2579.

### CODE REVIEW

File: lib/common/include/scipp/common/numeric.h [hunk 1]
```diff
@@ -98,21 +98,26 @@ constexpr auto pow(const B base, const E exponent) noexcept {
   }
 }
 
-template <class T> bool isnan([[maybe_unused]] T x) {
+template <class T> bool isnan([[maybe_unused]] const T &x) {
```
Comment (SimonHeybrock) [inline lib/common/include/scipp/common/numeric.h:101]: I am not happy that I had to change this to `const &`, but otherwise I'd have to pass also the large types (for now: `Eigen::Vector3d`) by value. For some `Eigen` types this is even forbidden completely. Is there a better way?

Comment (jl-wynen) [reply lib/common/include/scipp/common/numeric.h:101]: I don't think this causes any harm. This function will probably be optimized away anyway.

File: lib/core/include/scipp/core/element/special_values.h [hunk 2]
```diff
@@ -60,15 +56,15 @@ template <typename T> auto isneginf(T x) {
 } // namespace detail
 
 constexpr auto isposinf =
-    overloaded{special_value_args,
+    overloaded{special_value_args<>,
```
Comment (jl-wynen) [inline lib/core/include/scipp/core/element/special_values.h:59]: Are this and `isneginf` not supported by Eigen?

File: lib/core/test/element_special_values_test.cpp [hunk 3]
```diff
@@ -312,3 +313,53 @@ TYPED_TEST(ElementNegativeInfToNumTest, value_and_variance_out) {
...
+
+TEST(ElementSpecialValueVector3dTest, isinf_true_if_one_element_is_inf) {
+  Eigen::Vector3d v(1.0, 2.0, std::numeric_limits<double>::infinity());
+  EXPECT_TRUE(element::isinf(v));
+}
+
+TEST(ElementSpecialValueVector3dTest, isinf_false_if_no_element_is_inf) {
+  Eigen::Vector3d v(1.0, 2.0, 3.0);
+  EXPECT_FALSE(element::isinf(v));
+}
```
Comment (jl-wynen) [inline lib/core/test/element_special_values_test.cpp:365]: Add `isinf_false_if_one_element_is_nan`?

**Review by jl-wynen — COMMENTED** [review]
Wasn't there something you wanted to discus?

File: lib/core/include/scipp/core/element/special_values.h (hunk 2 above)
Comment (SimonHeybrock) [reply lib/core/include/scipp/core/element/special_values.h:59]: I don't think they make sense (unless you want to support them element-wise): You can have `sc.vector([INF, -INF, 0])`, what would this return?

**Comment by SimonHeybrock** [comment]
> Wasn't there something you wanted to discus?

Yes, mainly how to deal with this for the variety of other spatial dtypes we have, without having to write specializations for all of them. But then I thought we can postpone that (deal with it separately) so we can fix the `nanmean` bug more quickly.

File: lib/core/test/element_special_values_test.cpp (hunk 3 above)
Comment (SimonHeybrock) [reply lib/core/test/element_special_values_test.cpp:365]: It is in line 337?

File: lib/core/include/scipp/core/element/special_values.h (hunk 2 above)
Comment (jl-wynen) [reply lib/core/include/scipp/core/element/special_values.h:59]: Good point. Leave them out

File: lib/core/test/element_special_values_test.cpp (hunk 3 above)
Comment (jl-wynen) [reply lib/core/test/element_special_values_test.cpp:365]: Oh, right. In my head I was grouping them differently than their order in the file.
