### PR TITLE
Modified exception message and added relevant checks.

### LINKED ISSUE #1130: Coord mismatch should print coord name
A coordinate mismatch in e.g., a binar operation between data arrays prints the mismatching coord, but not the name/label of the offending coord.

Fix the exception in this case to include the relevant information.

### PR DESCRIPTION
**Pull request by rozyczko**
Fixes #1130

### CODE REVIEW

File: dataset/data_array.cpp [hunk 1]
```diff
@@ -319,6 +319,7 @@ DataArray &DataArray::operator/=(const VariableConstView &other) {
 
 DataArray operator+(const DataArrayConstView &a, const DataArrayConstView &b) {
   if (a.hasData() && b.hasData()) {
+    expect::coordsAreSuperset(a, b);
```
Comment (SimonHeybrock) [inline dataset/data_array.cpp:322]: This should not be here. `coordsAreSuperset` is an assymetric check for in-place operations and in particular does not support broadcasting (in-place output cannot be larger). The check for compatible coords happens in `union_` below (and broadcasting is permitted).

File: dataset/except.cpp [hunk 2]
```diff
@@ -10,8 +10,12 @@ namespace scipp::dataset::expect {
 void coordsAreSuperset(const DataArrayConstView &a,
                        const DataArrayConstView &b) {
   for (const auto &[dim, coord] : b.coords())
-    if (a.coords()[dim] != coord)
-      throw except::CoordMismatchError("Expected coords to match.");
+    if (a.coords()[dim] != coord) {
+      const std::string msg = "Mismatched coordinates: \"" + to_string(dim) +
+                              "\"\n" + to_string(a.coords()[dim]) +
+                              to_string(b.coords()[dim]);
+      throw except::CoordMismatchError(msg);
```
Comment (SimonHeybrock) [inline dataset/except.cpp:17]: Maybe add an overload to `CoordMismatchError` constructor that builds this string?

File: common/include/scipp/common/except.h [hunk 3]
```diff
@@ -24,6 +24,11 @@ template <class T> struct MismatchError : public Error<T> {
   template <class A, class B>
   MismatchError(const A &a, const std::initializer_list<B> b)
       : Error<T>(a, " expected to be equal to one of " + to_string(b)) {}
+
+  template <class A, class B>
+  MismatchError(const A &a, const B &b, const std::string &c)
+      : Error<T>(a, " expected to be equal to " + to_string(b) +
+                        "Mismatched coordinate: " + c) {}
```
Comment (SimonHeybrock) [inline common/include/scipp/common/except.h:31]: `MismatchError` is a generic piece of code (in the generic `common/` module/folder) and should therefore not contain anything referencing more specific concepts such as coordinates. This is what I meant on Slack by saying it could be ok to pass the extra message as a whole (`"Mismatched coordinate: " + dim.name()`), or to use the other option of providing `to_string`.

File: dataset/except.cpp [hunk 4]
```diff
@@ -10,8 +10,11 @@ namespace scipp::dataset::expect {
 void coordsAreSuperset(const DataArrayConstView &a,
                        const DataArrayConstView &b) {
   for (const auto &[dim, coord] : b.coords())
-    if (a.coords()[dim] != coord)
-      throw except::CoordMismatchError("Expected coords to match.");
+    if (a.coords()[dim] != coord) {
+      const std::string msg = "Mismatched coordinates: \"" + to_string(dim) +
+                              "\"\n" + to_string(a.coords()[dim]) +
+                              to_string(b.coords()[dim]);
```
Comment (SimonHeybrock) [inline dataset/except.cpp:16]: I think this defeats to purpose of adding the new exception constructor, since you end up not using it here.

File: variable/include/scipp/variable/string.h [hunk 5]
```diff
@@ -25,6 +25,10 @@ SCIPP_VARIABLE_EXPORT std::ostream &operator<<(std::ostream &os,
 
 SCIPP_VARIABLE_EXPORT std::string to_string(const Variable &variable);
 SCIPP_VARIABLE_EXPORT std::string to_string(const VariableConstView &variable);
+SCIPP_VARIABLE_EXPORT std::string
+to_string(const std::pair<Dim, VariableConstView> &coord);
+SCIPP_VARIABLE_EXPORT std::string
+to_string(const std::pair<std::string, VariableConstView> &attr);
```
Comment (rozyczko) [inline variable/include/scipp/variable/string.h:31]: `attr` is probably a leftover from copy-paste, should be `&vcoord` but completely benign and unimportant

Comment (SimonHeybrock) [reply variable/include/scipp/variable/string.h:31]: This is on purpose: For coords it should hit the overload in line 29 (key is `Dim`). For attributes (and masks) the key is `std::string`.
