### PR TITLE
Fix cppcheck warnings

### LINKED ISSUE #2291: Reduce cppcheck errors and false positives
- See https://github.com/scipp/scipp/blob/0f804a128b0ed2cf0ca4f3986d339f2ce1d254c2/lib/CMakeLists.txt#L177-L189 for up-to-date setup.
- If complete, replace current cppcheck CI stage with a cmake-based cppcheck run.

### PR DESCRIPTION
**Pull request by jl-wynen**
Fixes #2291

Please review if the suppressions make sense!

### CODE REVIEW

File: lib/common/test/numeric_test.cpp [hunk 1]
```diff
@@ -20,7 +20,6 @@ TEST(NumericPowTest, value_float_exponent) {
   EXPECT_TRUE(numeric::isnan(numeric::pow(-3, 3.2)));
   EXPECT_TRUE(numeric::isnan(numeric::pow(-3.0, -3.2)));
   EXPECT_TRUE(numeric::isnan(numeric::pow(-3, -3.2)));
-  EXPECT_TRUE(numeric::isinf(numeric::pow(0, -3.2)));
```
Comment (SimonHeybrock) [inline lib/common/test/numeric_test.cpp:23]: Why removed?

File: lib/core/include/scipp/core/element_array.h [hunk 2]
```diff
@@ -125,7 +120,7 @@ template <class T> class element_array {
       m_data.reset();
       m_size = 0;
     } else if (new_size != size()) {
-      m_data = make_unique_for_overwrite<T[]>(new_size);
+      m_data = std::make_unique_for_overwrite<T[]>(new_size);
```
Comment (SimonHeybrock) [inline lib/core/include/scipp/core/element_array.h:123]: Hooray :)

File: lib/dataset/test/bins_test.cpp [hunk 3]
```diff
@@ -464,6 +464,7 @@ TEST_F(DatasetBinsTest, concatenate) {
   check();
   buffer0.setData("b", column * column);
   check_fail();
+  // cppcheck-suppress duplicateExpression  # Intentional, see above.
```
Comment (SimonHeybrock) [inline lib/dataset/test/bins_test.cpp:467]: What is duplicate here (in the eyes of cppcheck)?

File: lib/python/bind_units.cpp [hunk 4]
```diff
@@ -74,6 +74,7 @@ void init_units(py::module &m) {
       .def(py::self + py::self)
       .def(py::self - py::self)
       .def(py::self * py::self)
+      // cppcheck-suppress duplicateExpression
```
Comment (SimonHeybrock) [inline lib/python/bind_units.cpp:77]: What is duplicate?

File: lib/python/variable.cpp [hunk 5]
```diff
@@ -90,44 +90,58 @@ of variances.)");
            "Rename dimensions.")
       .def_property_readonly("dtype", &Variable::dtype)
       .def(
-          "__radd__", [](Variable &a, double &b) { return a + b * units::one; },
+          "__radd__",
+          [](const Variable &a, const double &b) { return a + b * units::one; },
```
Comment (SimonHeybrock) [inline lib/python/variable.cpp:94]: This looks really odd. Should the `double` params be passed by value instead?

File: lib/variable/test/variable_keyword_args_constructor_test.cpp [hunk 6]
```diff
@@ -67,10 +67,6 @@ TEST(CreateVariableTest, from_vector) {
   EXPECT_EQ(makeVariable<double>(Dims{Dim::X}, Shape{3},
                                  Values(std::vector<int>{1, 2, 3})),
             makeVariable<double>(Dims{Dim::X}, Shape{3}, Values{1, 2, 3}));
-
-  const std::vector<double> v{1, 2, 3};
-  auto varRef = makeVariable<double>(Dims{Dim::X}, Shape{3}, Values{1, 2, 3});
-  auto var = makeVariable<double>(Dims{Dim::X}, Shape{3}, Values(v));
```
Comment (SimonHeybrock) [inline lib/variable/test/variable_keyword_args_constructor_test.cpp:73]: This might have served as a test that it compiles? Maybe it should not be removed?

**Review by SimonHeybrock — COMMENTED** [review]
Thanks for this probably tedious work, and the good explanation on why warnings are disabled!

File: lib/common/test/numeric_test.cpp (hunk 1 above)
Comment (jl-wynen) [reply lib/common/test/numeric_test.cpp:23]: `std::pow(0, <negative float>)` is undefined according to cppcheck.

File: lib/core/include/scipp/core/element_array.h (hunk 2 above)
Comment (jl-wynen) [reply lib/core/include/scipp/core/element_array.h:123]: Not supported by AppleClang yet :(
```
/Users/runner/work/1/s/lib/core/include/scipp/core/element_array.h:123:21: error: no member named 'make_unique_for_overwrite' in namespace 'std'
      m_data = std::make_unique_for_overwrite<T[]>(new_size);
```

File: lib/dataset/test/bins_test.cpp (hunk 3 above)
Comment (jl-wynen) [reply lib/dataset/test/bins_test.cpp:467]: Because of `column / column` which is always 1-like.

File: lib/python/bind_units.cpp (hunk 4 above)
Comment (jl-wynen) [reply lib/python/bind_units.cpp:77]: `py::self / py::self`

File: lib/python/variable.cpp (hunk 5 above)
Comment (jl-wynen) [reply lib/python/variable.cpp:94]: Yes. But I didn't change that here...

File: lib/variable/test/variable_keyword_args_constructor_test.cpp (hunk 6 above)
Comment (jl-wynen) [reply lib/variable/test/variable_keyword_args_constructor_test.cpp:73]: Or it is a leftover from a refactor? I can put it back and add an equivalent assertion to the one above.

File: lib/core/include/scipp/core/element_array.h (hunk 2 above)
Comment (jl-wynen) [reply lib/core/include/scipp/core/element_array.h:123]: Turns out, not even gcc supports it officially.

**Review by SimonHeybrock — APPROVED** [review]
