### PR TITLE
Various cleanup and small fix

### LINKED ISSUE #1929: `groupby` uses wrong init values for empty bins
```python
import scipp as sc
import numpy as np
N = 50
a = sc.DataArray(
    data=sc.Variable(['x'], values=np.ones(N)),
    coords = {'param': sc.Variable(['x'], values=np.random.rand(N))})
param = sc.array(dims=['param'], values=[0.0,0.00001,1.0])
sc.groupby(a, 'param', bins=param).min('x')
```
Compare to a normal reduction with 0 contributions where we setup values correctly using `special_like`.

Related to this: probably for the same reason these ops do not support masks.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
- Fixes #1929 
- Remove some unused code and other small cleanup

### CODE REVIEW

File: dataset/groupby.cpp [hunk 1]
```diff
@@ -140,20 +141,17 @@ template <void (*Func)(Variable &, const Variable &)>
 // requiring the introduction of a wrapping struct to aid compiler
 // resolution.
 struct wrap {
+  template <variable::FillValue fill>
   static constexpr auto reduce_idempotent =
       [](auto &&out, const auto &data_container,
          const GroupByGrouping::group &group, const Dim reductionDim,
          const Variable &mask) {
-        bool first = true;
+        copy(special_like(out, fill), out);
```
Comment (jl-wynen) [inline dataset/groupby.cpp:149]: Add an out arg to `special_like` or (maybe better) add a `fill` function instead? Would avoid doing two passes over the data and creating a temporary.

File: dataset/sort.cpp [hunk 2]
```diff
@@ -27,7 +16,7 @@ Variable sort(const Variable &var, const Variable &key, const SortOrder order) {
 DataArray sort(const DataArray &array, const Variable &key,
                const SortOrder order) {
   auto helper = array;
-  const auto dummy = nonclashing_name(helper.coords());
+  const Dim dummy = Dim::Internal0;
```
Comment (jl-wynen) [inline dataset/sort.cpp:19]: This does not work if the caller of `sort` already inserted `Dim::Internal0` for some reason.

**Review by jl-wynen — COMMENTED** [review]
Why did you remove permute and reverse? They could come in handy for some users.

I am not happy with groupby-reduction returning values that do not exist in the input. Would it make more sense to drop the empty bins? Probably not because that violates the expectation of getting a specific number of outputs.
At least the proposed solution is better than the old because it means that (with some hypothetical functions) `g.min('x').group_in('y').min('y') == `g.min('y').group_in('x').min('x')`. But `g.min('x').sum()` can produce bogus results and there is no real way of filtering out bad elements. Unless the reduction creates a new mask.

**Comment by SimonHeybrock** [comment]
> Why did you remove permute and reverse? They could come in handy for some users.

- `reverse` should be `flip` and rewritten to just setup strides, there was little use for the old code.
- Permute seemed specialized and untested. If something like this isreally required it should be done with more thought. And as with `sort`, something similar can be achieved using `groupby` (probably faster, since multi-threaded), so again it should just be rewritten and redesigned if needed.


> I am not happy with groupby-reduction returning values that do not exist in the input. Would it make more sense to drop the empty bins? Probably not because that violates the expectation of getting a specific number of outputs.

This is to make it consistent with our normal reduction operations, they do the same. And you *cannot* escape from this by dropping empty bins: A similar effect occurs with masks, if all contributing elements to a bin are masked, and masks may also differ along extra dims. Also, you can't have gaps between bins, so dropping isn't even possible, and it would make the output random and unpredictable when running the same with different random data as input.

> At least the proposed solution is better than the old because it means that (with some hypothetical functions) `g.min('x').group_in('y').min('y') == `g.min('y').group_in('x').min('x')`. But `g.min('x').sum()` can produce bogus results and there is no real way of filtering out bad elements. Unless the reduction creates a new mask.

I don't think we can automatically add masks. If bad elements are a concern, the user could run another `groupby` that just counts the number of contributions (this is not implemented, but would be simple to add) and use that as a mask.

File: dataset/sort.cpp (hunk 2 above)
Comment (SimonHeybrock) [reply dataset/sort.cpp:19]: If this turns out to be a problem we may need to switch to function-specific internal flags. At this point I think this is unlikely to happen.

File: dataset/groupby.cpp (hunk 1 above)
Comment (SimonHeybrock) [reply dataset/groupby.cpp]: I would have said "premature optimization", but actually I managed to refactor nicely, at the same time also enabling a working `groupby().sum()` for `bool`, which previously failed since it created output of type `bool`. See update.

File: dataset/sort.cpp (hunk 2 above)
Comment (jl-wynen) [reply dataset/sort.cpp:19]: But it would be painful to figure out once it does happen.

**Review by jl-wynen — APPROVED** [review]

File: dataset/sort.cpp (hunk 2 above)
Comment (SimonHeybrock) [reply dataset/sort.cpp]: Changed to dedicated dim IDs
