### PR TITLE
Fix comparison with variances and add "values" and "variances" helpers

### LINKED ISSUE #1182: values and variances extraction functions
This requirement has come up more than once in the past:
```python
values = sc.values(var) # returns variable containing only the values
variances = sc.variances(var) # returns variable containing only the variances (as values)
```
I had tried adding this previously, but there are some subtleties in the transition between variables with variances and without in the implementation of `transform` that need to be fixed, so this is not trivial.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Recently added support for comparing with variances in #1215 was actually broken. This is fixed here by adding a new flag for transform to disable variances in the output. Ideally we would like to detect this automatically, but in practice this is really tricky with combinations of generic lambdas, event lists, manually disabled or required variances on inputs, ...

With this change to `transform` it was finally possible to also fix #1182, adding `sc.values` and `sc.variances` as two useful helpers.

### CODE REVIEW

File: core/include/scipp/core/element/util.h [hunk 1]
```diff
@@ -41,4 +42,24 @@ template <class T> void zero(const core::ValueAndVariance<span<T>> &data) {
   zero(data.variance);
 }
 
+constexpr auto values =
+    overloaded{transform_flags::no_out_variance,
+               core::element::arg_list<double, float>, [](const auto &x) {
+                 if constexpr (is_ValueAndVariance_v<std::decay_t<decltype(x)>>)
+                   return x.value;
+                 else
+                   return x;
```
Comment (OwenArnold) [inline core/include/scipp/core/element/util.h:51]: Minor comment - This is also returning `unit` might be nicer to have a separate lambda for that as below.

File: python/operations.cpp [hunk 2]
```diff
@@ -133,4 +134,18 @@ void init_operations(py::module &m) {
 
   bind_contains_events<Variable>(m);
   bind_contains_events<DataArray>(m);
+
```
Comment (OwenArnold) [inline python/operations.cpp:137]: Description is probably enough, but could have been put in a "decompose" submodule.
