### PR TITLE
Avoid division by zero in `__sizeof__`

### LINKED ISSUE #1555: Exception when printing empty binned DataArrays
This creates and empty DataArray with bins
```.py
v = sc.Variable(dims=['x'], values=[])
d = sc.DataArray(data=v,
                coords={'x': sc.Variable(['x'], values=[])})
b = sc.bin(d, [sc.Variable(['x'], values=[0.0, 1.0])])
b
```
and raises
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.conda/envs/scipp-developer/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/Work/scipp-devel/install/scipp/table_html/__init__.py in make_html(container)
     12         return variable_repr(container)
     13     else:
---> 14         return dataset_repr(container)
     15 
     16 

~/Work/scipp-devel/install/scipp/table_html/formatting_html.py in dataset_repr(ds)
    464     obj_type = "scipp.{}".format(type(ds).__name__)
    465     header_components = [
--> 466         f"<div class='xr-obj-type'>{escape(obj_type)}"
    467         f" ({human_readable_size(sys.getsizeof(ds))})</div>"
    468     ]

ValueError: __sizeof__() should return >= 0
```
It also prints (as plain text, not HTML)
```
<scipp.DataArray>
Dimensions: {{x, 1}}
Coordinates:
  x                         float64    [dimensionless]  (x [bin-edge])  [0.000000, 1.000000]
Data:
                            DataArrayView  [dimensionless]  (x)  [<scipp.DataArrayView>
Dimensions: {{x, 0}}
Coordinates:
  x                         float64    [dimensionless]  (x)  []
Data:
                            float64    [dimensionless]  (x)  []

]
```

Outputting `v` or `d` works.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #1555.

### CODE REVIEW

File: dataset/util.cpp [hunk 1]
```diff
@@ -14,8 +16,10 @@ template <class T>
 scipp::index size_of_bucket_impl(const VariableConstView &view) {
   const auto &[indices, dim, buffer] = view.constituents<T>();
   const auto &[begin, end] = unzip(indices);
+  // Using max to avoid division by zero. Other factors should be zero in this
+  // case, so this should not influence the result.
   const auto scale = sum(end - begin).template value<scipp::index>() /
```
Comment (jl-wynen) [inline dataset/util.cpp:21]: A minor thing:
> Other factors should be zero in this case

How about using these factors instead:
```.cpp
const auto distance = sum(end - begin).template value<scipp::index>();
const auto scale = distance != 0 ? distance / static_cast<double>(buffer.dims()) : 0;
```
If the assumption turns out to be false, this would still trigger the exception in Python.

**Review by jl-wynen — APPROVED** [review]
