### PR TITLE
Change `flatten` to drop bin edges on mismatch, instead of raising

### LINKED ISSUE #2640: `flatten` should drop bin-edge coordinates that cannot be joined
This would make `flatten` more useful, in particular when working with binned data. Dropping bin-edge coords here would be consistent with similar behavior in https://scipp.github.io/user-guide/slicing.html#Advanced-indexing.

Can this create hidden bugs? Usually not: If a coord is missing after flatten, future operations that require the coord will fail, or a plot will not have axis tic labels, i.e., the missing coord comes obvious to the user.

Another example if binning/histogramming after a call to `flatten`:

```python
# ok, uses binned.bins.coords['Q'] to bin, flatten throws away "useless" bin coord
binned.flatten(to='dummy').bin(Q=100) 
# fails, since we do not have Q coord any more, user is immediately aware of the problem
hist.flatten(to='dummy').bin(Q=100)
```

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2640.

### CODE REVIEW

File: lib/dataset/dataset_operations_common.h [hunk 1]
```diff
@@ -125,10 +125,16 @@ Dataset apply_to_items(const Dataset &d, Func func, Args &&...args) {
 
 /// Return a copy of map-like objects such as Coords with `func` applied to each
 /// item.
+///
+/// If `func` return an invalid object it will not be inserted into the output
```
Comment (jl-wynen) [inline lib/dataset/dataset_operations_common.h:129]:
```suggestion
/// If `func` returns an invalid object it will not be inserted into the output
```

File: lib/dataset/dataset_operations_common.h [hunk 2]
```diff
@@ -125,10 +125,16 @@ Dataset apply_to_items(const Dataset &d, Func func, Args &&...args) {
...
+/// map. This can be used to drop/filter items.
 template <class T, class Func> auto transform_map(const T &map, Func func) {
   std::unordered_map<typename T::key_type, typename T::mapped_type> out;
-  for (const auto &[key, item] : map)
-    out.emplace(key, func(item));
+  for (const auto &[key, item] : map) {
+    auto transformed = func(item);
+    if (transformed.is_valid())
+      out.emplace(key, transformed);
```
Comment (jl-wynen) [inline lib/dataset/dataset_operations_common.h:136]:
```suggestion
      out.emplace(key, std::move(transformed));
```
?

**Review by jl-wynen — APPROVED** [review]
