### PR TITLE
Strip bin-edge coords in groupby.copy

### LINKED ISSUE #2260: `groupby(..).copy()` with bin edges -- bug or feature?
Consider
```python
import numpy as np
import scipp as sc
N = 20
x = sc.linspace(dim='x', start=0, stop=1, num=N+1, unit='m')
y = sc.array(dims=['x'], values=np.random.randint(0,2,N))
data = sc.array(dims=['x'], values=np.random.randint(0,2,N))
da = sc.DataArray(data=data, coords={'x':x, 'y':y})
```
then
```python
da.groupby('y').copy(0)
```
Here subgroups are copied into the output, including bin-edge coord `x`. Each subgroup has its own edges, and the last edge of subgroup `N` gets overwritten by the first edge of subgroup `N+1`. Run the example a couple of time to understand the effect.

Is this a bug, or a feature?

Other options would be:
- Drop bin-edge coords.
- Throw an exception (not useful, would throw in almost all cases).
- Other?

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fix #2260.

### CODE REVIEW

File: lib/dataset/groupby.cpp [hunk 1]
```diff
@@ -67,7 +67,9 @@ auto copy_impl(const Slices &slices, const Data &data, const Dim dim,
 template <class T>
 T GroupBy<T>::copy(const scipp::index group,
                    const AttrPolicy attrPolicy) const {
-  return copy_impl(groups()[group], m_data, dim(), attrPolicy);
+  const Dim slice_dim = m_data.coords()[dim()].dim();
+  return copy_impl(groups()[group], strip_edges_along(m_data, slice_dim), dim(),
+                   attrPolicy);
```
Comment (jl-wynen) [inline lib/dataset/groupby.cpp:72]: Are other operations affected by this?

Comment (SimonHeybrock) [reply lib/dataset/groupby.cpp:72]: If you refer to other groupby operations: No, because all other operations are "reduction" operations, so any meta data (coord, ...) that depends on that dimension is dropped anyway, just like `da.sum('x')` will not have an `'x'` coord any more.

**Review by jl-wynen — APPROVED** [review]
