### PR TITLE
Fix new segfault from `_repr_html_` with binned data

### LINKED ISSUE #3009: Kernel crash introduced by #2995
```python
import scipp as sc

table = sc.data.table_xyz(1000)
table.masks['mask'] = table.coords['x']
table.attrs['attrs'] = table.coords['x']
da = table.bin(x=10)
da.attrs['attr'] = sc.scalar(sc.DataArray(sc.scalar(1.2)))
da[0:0].copy()
```
.. because the new implementation is using `var.values[0]` somewhere.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
- Fixes #3009.
- Fix inconsistent "binned data:" prefix.
- Fix inconsistent `[...]`.
- Add `dim` and `content` to improve clarity.

### CODE REVIEW

File: lib/dataset/variable_instantiate_bin_elements.cpp [hunk 1]
```diff
@@ -55,18 +55,19 @@ dict_to_compact_string(const scipp::dataset::SizedDict<Key, Value> &dict,
 
 template <>
 std::string Formatter<core::bin<DataArray>>::format(const Variable &var) const {
-  const auto &buffer = var.bin_buffer<DataArray>();
-  std::string margin(8, ' ');
+  const auto &[indices, dim, buffer] = var.constituents<DataArray>();
+  std::string margin(10, ' ');
```
Comment (nvaytet) [inline lib/dataset/variable_instantiate_bin_elements.cpp:59]: I think we should limit the line length a little more (in `dict_to_compact_string`), as this no longer wraps so well in the html repr?
Screenshot at 2023-01-24 10-58-17

Or have a better rule for when to wrap? I think currently I'm checking if the line is too long after having added to the line, while we should probably check before appending whether the new addition will cause the line to overflow and break before appending?

File: src/scipp/html/formatting_html.py [hunk 2]
```diff
@@ -126,19 +126,12 @@ def _short_data_repr_html_non_events(var, variances=False):
 
 
 def _short_data_repr_html_events(var):
-    if isinstance(var, sc.Dataset):
-        return str(var)
-    underlying = var.values[0]
```
Comment (nvaytet) [inline src/scipp/html/formatting_html.py:131]: Could you also add a test that catches the segfault? e.g. the code snippet from the issue?

File: lib/dataset/variable_instantiate_bin_elements.cpp [hunk 3]
```diff
@@ -55,18 +55,19 @@ dict_to_compact_string(const scipp::dataset::SizedDict<Key, Value> &dict,
...
   std::stringstream s;
-  s << "\n" << margin << "dims=" << labels_to_string(buffer.data().dims());
+  s << "binned data: dim='" + to_string(dim) + "', content=DataArray(";
+  s << "\n" << margin << "dims=" << to_string(buffer.dims()) << ',';
```
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/dataset/variable_instantiate_bin_elements.cpp:62]: It is repeated, since in principle the content can move more than 1 dim. I think the length of the content can be important for debugging?

File: lib/dataset/variable_instantiate_bin_elements.cpp [hunk 4]
```diff
@@ -55,18 +55,19 @@ dict_to_compact_string(const scipp::dataset::SizedDict<Key, Value> &dict,
 
 template <>
 std::string Formatter<core::bin<DataArray>>::format(const Variable &var) const {
-  const auto &buffer = var.bin_buffer<DataArray>();
-  std::string margin(8, ' ');
+  const auto &[indices, dim, buffer] = var.constituents<DataArray>();
+  std::string margin(10, ' ');
   std::stringstream s;
-  s << "\n" << margin << "dims=" << labels_to_string(buffer.data().dims());
+  s << "binned data: dim='" + to_string(dim) + "', content=DataArray(";
```
[the remark this answers is not in the document]
Comment (SimonHeybrock) [reply lib/dataset/variable_instantiate_bin_elements.cpp:61]: No, there can be multiple (albeit rare in practice).

File: src/scipp/html/formatting_html.py (hunk 2 above)
Comment (SimonHeybrock) [reply src/scipp/html/formatting_html.py:131]: There were test fails both in other PRs and on `main`.

Comment (nvaytet) [reply src/scipp/html/formatting_html.py:131]: Strange it wasn't failing on my PR...

**Review by nvaytet — APPROVED** [review]
