### PR TITLE
Fix boolean indexing of binned data

### LINKED ISSUE #2745: Advanced indexing using boolean mask with binned data is broken
```python
import scipp as sc

da = sc.data.table_xyz(10).bin(x=2)
da.data[sc.array(dims=['x'], values=[True, False])]  # works
da.data[sc.array(dims=['x'], values=[False, True])]  # raises BinnedDataError
```

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2745.

The new implementation also improves performance significantly (especially in non-binned data). This also improves `sort` performance (though the slices setup is still quite inefficient and in the future we probably want to use `copy_impl` from `groupby.cpp` directly instead of going via `groupby.copy`).

### CODE REVIEW

File: lib/dataset/bin.cpp [hunk 1]
```diff
@@ -31,8 +31,8 @@ namespace scipp::dataset {
 namespace {
 
 template <class T, class Builder>
-auto bin(const Variable &data, const Variable &indices,
-         const Builder &builder) {
+auto setup_and_apply(const Variable &data, const Variable &indices,
```
Comment (SimonHeybrock) [inline lib/dataset/bin.cpp:34]: No change in this file apart from function rename (there as a different function of the same name, and I ran into this the Nth time when considering a solution for the issue using a different approach).

**Review by jl-wynen — APPROVED** [review]
LGTM

File: lib/dataset/groupby.cpp [hunk 2]
```diff
@@ -292,28 +332,35 @@ template <class T> struct MakeGroups {
...
-      groups.emplace_back(std::move(item.second));
-    }
+    keys.reserve(scipp::size(indices));
+    groups.reserve(scipp::size(indices));
+    for (auto &item : indices)
+      keys.emplace_back(item.first);
+    core::parallel::parallel_sort(keys.begin(), keys.end(),
+                                  NanSensitiveLess<T>());
+    for (const auto &k : keys)
+      groups.emplace_back(std::move(indices.at(k)));
```
Comment (SimonHeybrock) [inline lib/dataset/groupby.cpp:361]: @jl-wynen cppcheck seems to dislike this, can you see why?

```
/home/runner/work/scipp/scipp/lib/dataset/groupby.cpp:361:47: error: Out of bounds access in expression 'indices.at(k)' because 'indices' is empty and 'at' may be non-zero. [containerOutOfBounds]
      groups.emplace_back(std::move(indices.at(k)));
                                              ^
/home/runner/work/scipp/scipp/lib/dataset/groupby.cpp:340:39: note: Assuming condition is false
    for (auto it = values.begin(); it != end;) {
                                      ^
/home/runner/work/scipp/scipp/lib/dataset/groupby.cpp:360:26: note: Assuming container is not empty
    for (const auto &k : keys)
                         ^
/home/runner/work/scipp/scipp/lib/dataset/groupby.cpp:361:47: note: Access out of bounds
      groups.emplace_back(std::move(indices.at(k)));
```
