### PR TITLE
Various cleanup

### LINKED ISSUE #1805: Show dtype of bin contents instead of bins in errors from transform
```python
---------------------------------------------------------------------------
DTypeError                                Traceback (most recent call last)
<ipython-input-4-5d2b303837b0> in <module>
      2 data = scn.load_nexus('../amor2020n000346_tweaked.nxs')
      3 data.coords['position'].unit = 'm'
----> 4 scn.convert(data, 'tof', 'wavelength', scatter=True)
DTypeError: Cannot apply operation to item dtypes VariableView_observer float64 
```

The actualy problem was that the binned data coord was `int32`, but `transform` wrongly includes the outer dtype in the error message.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
- Fix #1805 by including the inner dtype in the error.
- Make trigonometry functions work with binned data. I thought this was working previously, but apparently there was no test.
- Remove useless (due to shared-ownership refactor) rvalue overloads.
- Remove unused header.

### CODE REVIEW

File: variable/trigonometry.cpp [hunk 1]
```diff
@@ -9,99 +9,61 @@
...
 #include "scipp/variable/trigonometry.h"
+#include "scipp/variable/variable_factory.h"
 
 using namespace scipp::core;
 
 namespace scipp::variable {
 
 Variable sin(const Variable &var) {
-  auto out = empty(var.dims(), units::one, var.dtype());
+  auto out = variableFactory().empty_like(var, std::nullopt);
```
Comment (SimonHeybrock) [inline variable/trigonometry.cpp:19]: This is ugly and non-obvious, will look into unifying the various creation mechanism independently of this.

Comment (jl-wynen) [reply variable/trigonometry.cpp:19]: Would a function `empty_like` that simply calls the factory be enough?

File: variable/except.cpp [hunk 2]
```diff
@@ -14,3 +15,14 @@ void throw_mismatch_error(const variable::Variable &expected,
...
 }
 } // namespace scipp::except
+
+namespace scipp::variable {
+
+std::string pretty_dtype(const Variable &var) {
+  if (!is_bins(var))
+    return to_string(var.dtype());
+  return to_string(var.dtype()) +
+         "(dtype=" + pretty_dtype(variableFactory().elem_dtype(var)) + ")";
```
Comment (jl-wynen) [inline variable/except.cpp:25]: Example output:
`Cannot apply log to item dtypes VariableView(dtype=int64)`
Not quite sure this is the best solution. It might make more sense to just display the inner dtype. Or are there cases where it matters if there are bins or not?

Also (unrelated to this change), showing 'VariableView' does not really make sense. Can this be changed to something like 'bin(Variable)'?

File: variable/trigonometry.cpp (hunk 1 above)
Comment (SimonHeybrock) [reply variable/trigonometry.cpp:19]: Except that the vactory variance does not support settings things like unit, so it is not entirely trivial.

File: variable/except.cpp (hunk 2 above)
Comment (SimonHeybrock) [reply variable/except.cpp:25]: Yes I was wondering whether just showing the inner dtype would be enough, but it would be confusing: If someone got the error and then inspects the HTML view they would not see this printed dtype.

I agree that `VariableView` is not perfect, but I need to think a bit more about a solution. The problem is that in practice the elements behave like `Variable`, but we also have an actual `dtype=Variable`. Maybe `bin<Variable>` or something like that is really the best solution, but it is confusing since when accessed it actually behaves like `Variable`? `view<Variable>`?
