### PR TITLE
Obviate set on self assignment in MutableView

### LINKED ISSUE #911: Inplace math with slices of coord/labels/... does not work
```python
import scipp as sc
from scipp import Dim
import numpy as np

var = sc.Variable([Dim.X], shape=(4,))
d = sc.Dataset()
d['dummy'] = var
d.coords[Dim.X] = var
d.coords[Dim.X][Dim.X, 0:2] += 1.0 # works
d[Dim.X, 0:2].coords[Dim.X] += 1.0 # fails
```

The reason the latter fails is due to how Pythons in-place operators like `+=` work: The return value is assigned, i.e., this calls `__setitem__` as a final step. Scipp handles this by checking for self-assignment (aborting early for efficiency, see also #824). However, in the case of coords/labels/masks/attrs this check appears to happen *after* a sanity check that fails.

### PR DESCRIPTION
**Pull request by OwenArnold**
Fixes #911

 `__setitem__`  defined in `bind_mutable_view` still calls `set` on `MutableView`, but self assignment is checked and set is aborted. Values are changed prior to set as part of in place modifications `__getitem__`.

### CODE REVIEW

File: variable/include/scipp/variable/variable.h [hunk 1]
```diff
@@ -167,6 +167,7 @@ class SCIPP_VARIABLE_EXPORT Variable {
   VariableConcept &data() & { return *m_object; }
 
   void setVariances(Variable v);
+  auto &underlying() const { return *this; }
```
Comment (OwenArnold) [inline variable/include/scipp/variable/variable.h:170]: Should probably do this via a constexpr if or type trait solution rather than adding `underlying` to `Variable` class directly.

File: dataset/include/scipp/dataset/map_view.h [hunk 2]
```diff
@@ -252,6 +252,10 @@ template <class Base, class Access> class MutableView : public Base {
 
   template <class VarOrView>
   void set(const typename Base::key_type key, VarOrView var) const {
+    if (!m_access.writeable() && Base::contains(key) &&
```
Comment (SimonHeybrock) [inline dataset/include/scipp/dataset/map_view.h:255]: Why do you check for "not writable" here?

Comment (OwenArnold) [reply dataset/include/scipp/dataset/map_view.h:255]: I didn't originally have it, but causes problems in a few places such as here:

positions end up unset on monitors https://github.com/scipp/scipp/blob/master/python/src/scipp/compat/mantid.py#L507

Comment (SimonHeybrock) [reply dataset/include/scipp/dataset/map_view.h:255]: Not sure I understand, can you elaborate.

Comment (SimonHeybrock) [reply dataset/include/scipp/dataset/map_view.h:255]: @OwenArnold Looking at this again after our call: It feels wrong to add a special case where calling `set` on a const view passes. Should we add loop-holes (even irrelant loop-holes) to our C++ library due to the way Python works (calling `__setitem__` after `__getitem__`)? I feel the proper way should be to fix this in the Python bindings, skipping the `__setitem__` for self-assignment. On the other hand, this is also weird since it kind of duplicates the self-assignment check we have in `Variable`? Not sure what I am concluding here.

Comment (OwenArnold) [reply dataset/include/scipp/dataset/map_view.h:255]: Yes. Agree feels wrong to fix a python issue at the c++ level. I'm not sure how we can reasonably do this at the point of `__setitem__` How can we overload correctly? One idea I had is to check that the data being assigned is the same for the indices over which it is being assigned maybe?

Comment (SimonHeybrock) [reply dataset/include/scipp/dataset/map_view.h:255]: Well, you just need to move this check to `__setitem__`, I think?

Comment (OwenArnold) [reply dataset/include/scipp/dataset/map_view.h:255]: Ok. I'll see how that pans out.

Comment (SimonHeybrock) [reply dataset/include/scipp/dataset/map_view.h:255]: Something like:
```python
if (self.contains(key))
  self[key].assign(var);
else
  self.set(key, var);
```
maybe?

File: python/dataset.cpp [hunk 3]
```diff
@@ -12,6 +12,7 @@
 #include "scipp/dataset/rebin.h"
 #include "scipp/dataset/sort.h"
 #include "scipp/dataset/unaligned.h"
+#include <iostream>
```
Comment (SimonHeybrock) [inline python/dataset.cpp:15]: .

**Comment by SimonHeybrock** [comment]
@OwenArnold Should this still be a draft?
