### PR TITLE
Fix operations on transposed binned data; remove binned data operation overhead

### LINKED ISSUE #3277: Operations on transposed (or similar) binned data return incorrect values in bin-element coords/masks/attrs
Consider https://github.com/scipp/scipp/blob/5b12dc349fe8f2086cd1e237f5bb4a04dd2f6a62/lib/dataset/variable_instantiate_bin_elements.cpp#L90-L109
Note in particular the first TODO. This means
1. We cannot apply operations to a slice of binned data (without copying first), instead we get an exception since the buffer length is not matching up. This is not nice, but at least correct.
2. If indices are not in order, coords (and masks) are copied directly into the output buffer *without* reordering. The implicit length check is not a sufficient safe guard here. This is a bad bug.

Example:

```python
import scipp as sc

table = sc.data.table_xyz(10)
da = table.bin(x=2, y=2)
print('data:')
print(da['x', 1]['y', 0].bins.data.value.values)
print((da.transpose() * 1)['x', 1]['y', 0].bins.data.value.values)
print((da.transpose().copy())['x', 1]['y', 0].bins.data.value.values)
print('coords:')
print(da['x', 1]['y', 0].bins.coords['x'].value.values)
print((da.transpose() * 1)['x', 1]['y', 0].bins.coords['x'].value.values)
print((da.transpose().copy())['x', 1]['y', 0].bins.coords['x'].value.values)
```
Output:
```
data (correct):
[1.08584904 1.00868831]
[1.08584904 1.00868831]
[1.08584904 1.00868831]
coords (broken!):
[0.97669977 0.96407925]
[0.38019574 0.26169242]
[0.97669977 0.96407925]
```

Note the `copy()` uses a different code path and is thus correct.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #3277.

Reviewer: **Please consider the logic very carefully, I think it is probably not enough to look at the diff. Please also verify that we can indeed skip the bin-index validation.**

Add support for operations on slices of binned data, which raised previously.

Aside from these changes, I am avoiding overhead in the setup logic of binned variables (tracing down this overhead is what actually led me to discover the linked bug). For few bins this is not so relevant, but it becomes significant when we have many bins. This may also impact some benchmarks @YooSunYoung is running for data-streaming applications.

Examples:

```python
# binned data array, with data-array as content
da.copy()
da * 1
da.bins.concat()
```
For 50M bins and 100M events in `da`, times reduce from around 2 seconds to 0.7 seconds, i.e., we removed 1.3 seconds overhead. For 10M bins I see around 250 ms gain, i.e., we can see this is roughly proportional to the total bin count.

### CODE REVIEW

File: lib/dataset/test/binned_arithmetic_test.cpp [hunk 1]
```diff
@@ -77,3 +79,34 @@ TEST_F(BinnedArithmeticTest, var_and_array) {
   EXPECT_EQ(var_arr, make_bins(indices, Dim::Event, expected_array));
   EXPECT_EQ(arr_var, make_bins(indices, Dim::Event, expected_array));
 }
+
+TEST_F(BinnedArithmeticTest, op_on_transpose) {
+  const auto indices2d =
+      makeVariable<scipp::index_pair>(Dims{Dim::X, Dim::Y}, Shape{2, 2},
+                                      Values{std::pair{0, 1}, std::pair{1, 2},
+                                             std::pair{2, 4}, std::pair{4, 5}});
```
Comment (jl-wynen) [inline lib/dataset/test/binned_arithmetic_test.cpp:87]: Can you also add an empty bin?

File: lib/dataset/variable_instantiate_bin_elements.cpp [hunk 2]
```diff
@@ -99,13 +99,29 @@ class BinVariableMakerDataArray : public variable::BinVariableMaker<DataArray> {
...
-        variable::variableFactory().create(type, dims, unit, variances),
-        copy(source.coords()), copy(source.masks()), copy(source.attrs()));
-    // TODO is the copy needed?
-    return make_bins(copy(indices), dim, std::move(buffer));
+    // The only caller is BinVariableMaker::create, which should ensure that
+    // indices and buffer size are valid and compatible.
+    auto data_buffer =
+        variable::variableFactory().create(type, dims, unit, variances);
+    // If the buffer size is unchanged and input indices match output indices we
+    // can use a cheap and simply copy of the buffers coords and masks.
```
Comment (jl-wynen) [inline lib/dataset/variable_instantiate_bin_elements.cpp:107]:
```suggestion
    // can use a cheap and simple copy of the buffer's coords and masks.
```

File: lib/variable/variable_instantiate_bin_elements.cpp [hunk 3]
```diff
@@ -26,8 +26,8 @@ template <class T> class BinVariableMakerVariable : public BinVariableMaker<T> {
                           const bool variances) const override {
     // Buffer contains only variable, which is created with new dtype, no
     // information to copy from parent.
-    return make_bins(copy(indices), dim,
-                     variableFactory().create(type, dims, unit, variances));
+    return make_bins_no_validate(
+        indices, dim, variableFactory().create(type, dims, unit, variances));
```
Comment (jl-wynen) [inline lib/variable/variable_instantiate_bin_elements.cpp:30]: Can this now lead to sharing indices? Or is this function only called with a fresh set of indices that the user has no handle of?

**Review by jl-wynen — COMMENTED** [review]
The implementation looks good to me.

File: lib/variable/variable_instantiate_bin_elements.cpp (hunk 3 above)
Comment (SimonHeybrock) [reply lib/variable/variable_instantiate_bin_elements.cpp:30]: As far as I can tell it is always fresh, but please double check! The intention is that this does *not* lead to sharing.

Comment (jl-wynen) [reply lib/variable/variable_instantiate_bin_elements.cpp:30]: Looks like it is only called in one place and that passes in freshly created indices.

**Review by jl-wynen — APPROVED** [review]
