### PR TITLE
Fixes for copying binned structured data

### LINKED ISSUE #2641: Copying a field of a binned variable with elem dtype `vector3` raises
```python
import scipp as sc

table = sc.data.table_xyz(2)
table.coords['pos'] = sc.vectors(dims=['row'], values=[[1,2,3],[4,5,6]])
x = sc.linspace('x', 0, 1, num=2, unit='m')
binned = sc.bin(table, edges=[x])
binned.bins.coords['pos'].fields.x.copy()
```
fails.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Two fixes here:

- Fixes #2641.
- Fix a bug in `MultiIndex` for buffers with stride.
- Implement copy of binned data with structured buffer dtypes (such as vector, matrix, ...).

I spent a long time hunting down a bug I introduced during the fix. This was caused by a wrong instantiation (`ElementArrayModel` instead of `StructureArrayModel`) when using `transform` in `bin_array_model.h` due to visibility of specializations. I have not added a `static_assert` in `ElementArrayModel` which should catch more such problems at compile time in the future.

### CODE REVIEW

File: lib/variable/bins.cpp [hunk 1]
```diff
@@ -15,6 +16,17 @@
 
 namespace scipp::variable {
 
+/// Used internally by BinArrayModel to implement copying.
+///
+/// This is using transform, so only data (no coords, etc.) is copied, but we
+/// only use this for buffers of type Variable.
+void copy_data(const Variable &src, Variable &dst) {
```
Comment (jl-wynen) [inline lib/variable/bins.cpp:23]: I think it makes sense to put a (debug-build) check here along the lines of
```cpp
assert(src.dtype() == dtype<Variable>);
```

File: lib/variable/include/scipp/variable/variable.tcc [hunk 2]
```diff
@@ -55,6 +56,7 @@ auto make_model(const units::Unit unit, const Dimensions &dimensions,
                 element_array<T> values,
                 std::optional<element_array<T>> variances) {
   if constexpr (std::is_same_v<model_t<T>, ElementArrayModel<T>>) {
+    static_assert(!std::is_same_v<T, Eigen::Vector3d>);
```
Comment (jl-wynen) [inline lib/variable/include/scipp/variable/variable.tcc:59]: Why specifically vector? What about other structured dtypes?

File: lib/variable/test/variable_bin_test.cpp [hunk 3]
```diff
@@ -232,3 +234,38 @@ TEST_F(VariableBinsTest, setSlice) {
...
 }
+
+class VariableBinnedStructuredTest : public ::testing::Test {
+protected:
+  Dimensions dims{Dim::Y, 2};
+  Variable indices = makeVariable<scipp::index_pair>(
+      dims, Values{std::pair{0, 1}, std::pair{1, 3}});
+  Variable buffer = variable::make_vectors(Dimensions(Dim::X, 3), units::m,
+                                           {1, 2, 3, 4, 5, 6, 7, 8, 9});
+  Variable var = make_bins(indices, Dim::X, buffer);
```
Comment (jl-wynen) [inline lib/variable/test/variable_bin_test.cpp:245]: These are specific to `copy_vector`. Please move them there.

File: lib/variable/include/scipp/variable/variable.tcc (hunk 2 above)
Comment (SimonHeybrock) [reply lib/variable/include/scipp/variable/variable.tcc:59]: Oh, this is leftover from debugging...

**Review by jl-wynen — APPROVED** [review]
