### PR TITLE
Fix squeeze

### LINKED ISSUE #1868: `squeeze` incorrect when used on slices
This is due to incorrect handling of strides after the shared-ownership refactor

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #1868. `Variable::setDims()` did not take into account strides.

Note that `reshape` has the same bug since it also used `setDims()`, but there the fix is more complicated and I will provide it separately.

### CODE REVIEW

File: variable/shape.cpp [hunk 1]
```diff
@@ -163,15 +163,15 @@ Variable transpose(const Variable &var, const std::vector<Dim> &dims) {
...
-  auto squeezed = var.dims();
+Variable squeeze(const Variable &var, const std::vector<Dim> &dims) {
+  auto squeezed = var;
   for (const auto &dim : dims) {
-    if (squeezed[dim] != 1)
+    if (squeezed.dims()[dim] != 1)
       throw except::DimensionError("Cannot squeeze '" + to_string(dim) +
                                    "' since it is not of length 1.");
-    squeezed.erase(dim);
+    squeezed = squeezed.slice({dim, 0});
```
Comment (OwenArnold) [inline variable/shape.cpp:172]: 👍

**Review by OwenArnold — APPROVED** [review]
Looks good.

Orthogonal to this issue/PR was slightly surprised to see that squeeze has no python bindings. Is that deliberate? Not that I see it as a major problem.

**Comment by SimonHeybrock** [comment]
> Looks good.
> 
> Orthogonal to this issue/PR was slightly surprised to see that squeeze has no python bindings. Is that deliberate? Not that I see it as a major problem.

It was added quite recently as an implementation detail. Bindings could definitely be added.
