### PR TITLE
Multi-dim coord concept fix

### LINKED ISSUE #2057: Conceptually wrong association of N-D coords with dimensions
From [docs](https://scipp.github.io/user-guide/data-structures.html#Distinction-between-dimension-coords-and-non-dimension-coords,-and-coords-and-attrs): "*In the special case of non-dimension coords that have more than 1 dimension, they are considered to be labels for their inner dimension.*"

Now consider this data array, where `radius` and `phi` coords have been computed from `x` and `y`:

image

Slice the array along one of its dimensions:

image

Here `phi` is converted to an attribute because it is considered are coordinate of `x`. However, for such a coord it is just conincidence what its inner dimension is --- it isn't labelling *either* of the dims (or both, after slicing).

The conclusion seems to be that the current definition is wrong. In the above example the expected outcome would be that `radius` and `phi` behave in the same manner, and that slicing along `x` or `y` is that same: In all 4 cases either both or neither of `radius` and `phi` should turn into attributes.

Whether both or neither requires closer consideration.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2057. See ADR for details.

Reduction operations now no longer fail if there is a mismatch 2d coord, regardless of whether this coord is a dimension-coord or not. The main example where this is relevant for us would be summing spectra after conversion to a non-TOF unit such as `wavelength`. Wavelength bins would not match and the wavelength coord now gets dropped.

The main motivation for this is simplicity and avoidance of bugs / maintenance overhead. Otherwise defining what operations do becomes much more difficult and error prone.

### CODE REVIEW

File: dataset/dataset_operations_common.h [hunk 1]
```diff
@@ -45,51 +45,23 @@ template <class T> auto copy_map(const T &map) {
...
-    // copied.
+  const auto copy_independent = [&](auto &coords_, const auto &view,
+                                    const bool share) {
     for (auto &&[d, coord] : view)
-      if (coord.dims().ndim() == 0 || dim_of_coord(coord, d) != dim) {
-        if (aligned)
-          expectAlignedCoord(d, coord, dim);
-        if constexpr (ApplyToData) {
-          coords_.emplace(d, coord.dims().contains(dim)
-                                 ? func(coord, dim, args...)
```
Comment (SimonHeybrock) [inline dataset/dataset_operations_common.h:76]: I think this line was actually unreachable, indicating that old implementation was too complex.

File: core/sizes.cpp [hunk 2]
```diff
@@ -189,7 +189,7 @@ Sizes merge(const Sizes &a, const Sizes &b) {
 }
```
Comment (nvaytet) [inline core/sizes.cpp:189]: Having not looked at the code changes yet, I think dropping everything is the right behaviour.
It just makes things simpler (also conceptually).

**Comment by SimonHeybrock** [comment]
With these changes, we also get the following:

Before:
image

After:
image

Slightly better, but still odd? Thoughts @OwenArnold @nvaytet?

**Comment by nvaytet** [comment]
> Slightly better, but still odd? Thoughts @OwenArnold @nvaytet?

hmmm why do you think it's still odd?
The coordinates both depend on `y`, so when you slice them you just the get `x` component, i think that makes sense?

File: python/tests/transform_coords_test.py [hunk 3]
```diff
@@ -51,10 +51,6 @@ def ab(*, a, b):
     return a + b
 
 
-def ba(b, a):
```
Comment (nvaytet) [inline python/tests/transform_coords_test.py:54]: Why was this one removed?

Comment (SimonHeybrock) [reply python/tests/transform_coords_test.py:54]: This was part of the workaround #2086 which I reverted as part of this PR, since it it not necessary any more.

**Comment by SimonHeybrock** [comment]
> > Slightly better, but still odd? Thoughts @OwenArnold @nvaytet?
> 
> hmmm why do you think it's still odd?
> The coordinates both depend on `y`, so when you slice them you just the get `x` component, i think that makes sense?

The odd part is that before slicing `ds['x']` has neither of the coords (since the also depend on `y`), but after slicing it has both.

**Review by nvaytet — APPROVED** [review]
I think it looks good. I don't have anything to add.

**Comment by nvaytet** [comment]
Unless you want to wait until @jl-wynen is back so he can also have a look?

**Comment by SimonHeybrock** [comment]
> Unless you want to wait until @jl-wynen is back so he can also have a look?

A second pair of eyes would be good, yes, but can also be @OwenArnold.

File: docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+- Status: accepted
+- Deciders: Jan-Lukas, Neil, Owen, Simon
+- Date: 2021-08-19
+
+Context
+-------
+
+In the special case of non-dimension coords that have more than 1 dimension, they are considered to be labels for their inner dimension.
+This causes trouble in many cases, e.g., after computation of ``phi`` and ``radius`` for 2-D data from ``x`` and ``y`` coords.
+If for example ``phi.dims = ['x', 'y']`` and ``radius.dims = ['y', 'x']`` then and ``x`` slice will:
```
Comment (OwenArnold) [inline docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst:13]: "then and" doesn't make sense in this sentence.

File: python/src/scipp/html/formatting_html.py [hunk 5]
```diff
@@ -171,6 +170,23 @@ def summarize_mask(dim, var, ds=None):
     return summarize_variable(str(dim), var, is_index=False, embedded_in=ds)
 
 
+def find_bin_edges(var, ds):
+    """
+    Checks if the coordinate contains bin-edges.
```
Comment (OwenArnold) [inline python/src/scipp/html/formatting_html.py:175]: Function name is good, but comment implies we get a bool return.

**Review by OwenArnold — CHANGES_REQUESTED** [review]

File: python/src/scipp/html/formatting_html.py (hunk 5 above)
Comment (SimonHeybrock) [reply python/src/scipp/html/formatting_html.py:175]: I didn't change this, this is part of the `git revert` of https://github.com/scipp/scipp/pull/2086.

File: docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst (hunk 4 above)
Comment (SimonHeybrock) [reply docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst]: fixed

File: python/tests/transform_coords_test.py (hunk 3 above)
Comment (jl-wynen) [reply python/tests/transform_coords_test.py:54]: But the test still has to pass in order to implement robust unit conversions.

Comment (SimonHeybrock) [reply python/tests/transform_coords_test.py:54]: True, but isn't it a case of not re-testing basic assumptions (which was fixed here)? Also, "transposed" coords are now exercised by the test below where a TODO was removed.

**Comment by jl-wynen** [comment]
Coords with bin-edges are treated like dimension-coords for the bin edge when slicing. Is this what we want?
multi_dim_slicing

**Comment by SimonHeybrock** [comment]
> Coords with bin-edges are treated like dimension-coords for the bin edge when slicing. Is this what we want?

You mean, they are turned into attributes? Yes, I think this is what we want, otherwise it would prevent operations such as `da['y', 0] - da['y', 1]`, which is useful. Basicall we do the coord->attr mapping whenever it is clear which dimension a coord belongs to.

File: docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+This causes trouble in many cases, e.g., after computation of ``phi`` and ``radius`` for 2-D data from ``x`` and ``y`` coords.
+If for example ``phi.dims = ['x', 'y']`` and ``radius.dims = ['y', 'x']`` then an ``x`` slice will:
+
+- Convert ``radius`` to an attribute because it is considered a coordinate of ``x``.
+- Keep ``phi`` as a coordinate because it is considered a coordinate of ``y``.
+
+However, for such coords it is just coincidence what its inner dimension is --- it isn't labelling either of the dims (or both, after slicing).
+
+The conclusion seems to be that the current definition is wrong.
+In the above example the expected outcome would be that radius and phi behave in the same manner, and that slicing along x or y is behaves same, i.e., either both or neither of radius and phi should turn into attributes.
```
Comment (jl-wynen) [inline docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst:21]:
```suggestion
In the above example the expected outcome would be that radius and phi behave in the same manner, and that slicing along x or y behaves same, i.e., either both or neither of radius and phi should turn into attributes.
```

File: docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+
+A related limitation is that currently bin-edges must be edges for their inner dimension, because for dimension coords the matching coord key overrides which dimension the coord is associated with.
+As a consequence such a bin-edge coord exceeds the data dims in a dimension other than its associated dimension, which is not valid, raising an exception.
+
+Decision
+--------
+
+Do not associate multi-dimension coords with a dimension, unless:
+- It is a bin-edge coord, in which case it gets associated with the bin-edge dimension.
+- It is not a bin-edge coord, but a dimension coord, and gets associated with the coord key.
```
Comment (jl-wynen) [inline docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst:31]:
```suggestion
Do not associate multi-dimension coords with a dimension, unless:

 - It is a bin-edge coord, in which case it gets associated with the bin-edge dimension.
 - It is not a bin-edge coord, but a dimension coord, and gets associated with the coord key.
```
Indentation and empty line needed by sphinx.

File: docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+
+Positive:
+~~~~~~~~~
+
+- Fix inconsistent behavior.
+- Bin-edges work as expected in more cases.
+- Transposing is not necessary any more to work around limitations.
+- Reduction operations now drop multi-dimensional coords that depend on the reduction dimension.
+  This makes the operations more flexible while at the same time ensuring consistency, by dropping rather than preserving the coordinate.
+  Note that in rare cases this may lead to undesirable consequences, e.g., if the result of the reduction is later add to other that where the coord is present, which would be wrong.
```
Comment (jl-wynen) [inline docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst:44]: Grammar. Not exactly sure what you want to say here.

File: docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+
+Negative:
+~~~~~~~~~
+
+- It is no longer possible to define an associated dimension for multi-dimensional coords that label a particular dimension.
```
Comment (jl-wynen) [inline docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst:49]: Needed anywhere?

**Comment by jl-wynen** [comment]
It is now possible to have coordinates that are bin-edges in more than one dim. Slicing seems to treat them as non-dimension-coords. I think at the very least the latter is incorrect. But according to earlier discussions, I think we should avoid bin-edges in more than one dimension completely.

multi-edge-coord

Potential culprit: `Dict::dim_of` returns the first bin-edge dim without looking through the other dims.

File: docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst (hunk 9 above)
Comment (SimonHeybrock) [reply docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst:49]: Not that I know, can you think of a scenario?

**Comment by SimonHeybrock** [comment]
> It is now possible to have coordinates that are bin-edges in more than one dim. Slicing seems to treat them as non-dimension-coords. I think at the very least the latter is incorrect. But according to earlier discussions, I think we should avoid bin-edges in more than one dimension completely.
> 
> multi-edge-coord
> 
> Potential culprit: `Dict::dim_of` returns the first bin-edge dim without looking through the other dims.

Good catch. I think we should indeed just forbid this (even though one can imagine potential edge cases where it may be useful?).

**Comment by jl-wynen** [comment]
> (even though one can imagine potential edge cases where it may be useful?).

Maybe. But can our functions handle cases where the grid is not rectangular? I feel like multiple bin-edges would potentially introduce a lot of complication that the users might need to handle manually.

File: docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst (hunk 9 above)
Comment (jl-wynen) [reply docs/reference/developer/adr/0008-consistent-multi-dimensional-coords.rst:49]: No. Also, dimension-coords still kind of label the dimension with matching name. At least as far as slicing is concerned.

**Comment by SimonHeybrock** [comment]
@jl-wynen I believe I addressed your comments, please have another look.

File: python/tests/transform_coords_test.py (hunk 3 above)
Comment (jl-wynen) [reply python/tests/transform_coords_test.py:54]: Not sure if this is re-testing something. I would say we should have a test that ensures that the order of dimensions of newly computed coordinates does not matter in `transform_coords`.

Comment (SimonHeybrock) [reply python/tests/transform_coords_test.py:54]: But wouldn't it be better to have just tests that ensure that coords with arbitrary dim order can be added to a data array, rather than re-testing this contract (of `DataArray`) every time we implement something that relies on this contract?

Comment (jl-wynen) [reply python/tests/transform_coords_test.py:54]: > But wouldn't it be better to have just tests that ensure that coords with arbitrary dim order can be added to a data array

Isn't this what the test with `ba` did? Yes, the order is arbitrary in all tests, but it is always the same.

Comment (SimonHeybrock) [reply python/tests/transform_coords_test.py:54]: @jl-wynen I made the corresponding unit test more thorough now.
